### ISSUE TITLE
Zähler (NEU) im Dock wird nicht gelöscht

### ISSUE THREAD

**Issue by ghost** [pecuniabanking/pecunia-client#296]
_From [Egbert.S...@googlemail.com](https://code.google.com/u/105676784314097787653/) on April 02, 2014 17:17:39_

Hallo,
der Zähler (roter Kreis mit Zahl im Dock) der die neuen Buchungen
in der Liste zählt, wird nach dem Abarbeiten der Buchungen
nicht geöscht.
Erst nach einem Abruf mit null "neuen Buchungen" verschwindet er.

Nicht wirklich kritisch aber unschön.
Gruß

_Original issue: http://code.google.com/p/pecuniabanking/issues/detail?id=277_

**Comment by mike-lischke** [comment]
Ich glaube nicht, dass dieser Issue ein Duplikat von 266 ist. Dort geht es um etwas ganz anderes. Eher passt da schon #159.

**Comment by macalicious** [comment]
@mike-lischke Ich glaube beim damaligen issue-Import ist mit den Referenzen irgendwas schief gelaufen. Es sollte duplicate von https://github.com/pecuniabanking/pecunia-client/issues/285 heißen.

**Comment by mike-lischke** [comment]
Vielleicht ist das tatsächlich so gewesen im Allgemeinen. Hier jedoch wurde das Duplikat durch Frank angegeben. Aber egal, jetzt haben wir es ja :-)
