### ISSUE TITLE
Ausdruck einer durchgeführten Überweisung

### ISSUE THREAD

**Issue by ghost** [pecuniabanking/pecunia-client#331]
_From [webmurk...@gmail.com](https://code.google.com/u/106158644875422196916/) on July 07, 2014 22:17:29_

Wie kann das Problem reproduziert werden? 1.Registerkarte "Überweisungen"
2.Eine abgeschlossene Überweisung markieren
3.CMD+P bewirkt gar nichts, der Klick im Menü "Konto/Drucken..." schließt Pecunia - Absturz. Was ist das erwartete Ergebnis und was geschah stattdessen? Ich wollte eine Funktion finden wie ich eine getätigte Überweisung drucken kann, damit ich das als Nachweis mitnehmen kann. Leider gibt es außer der Liste von allen Buchungen (Zeitraum min. 1 Monat) keine andere Druckfunktion Welche Produktversion und welche OS Version wurde verwendet? Pecunia 1.1.1 - OSX 10.9.3 und 10.9.4 Weitere Informationen zum Problem bitte hier:

_Original issue: http://code.google.com/p/pecuniabanking/issues/detail?id=312_

**Comment by webmurkser** [comment]
Sorry, aber mit jeder Version die ich bisher nach dem schließen dieses Tickets ausprobiert habe, exisitert das Problem weiterhin. 
Einfach eine Buchung in der Übersicht anklicken, aus dem Menü "Konto" den Menüpunkt "Drucken..." auswählen und Pecunia ist weg. Yosemite 10.10.1 - Pecunia 1.1.3 (1.1.37) AppStore Version.
