### ISSUE TITLE
Pecunia Version 1.1.2  not compatible with OS-X Yosemite 10.10 

### ISSUE THREAD

**Issue by derMueller1** [pecuniabanking/pecunia-client#362]
used the Reiner SCT Komfort Card Reader.  Test for the unit by: ttp://forum.reiner-sct.com/in...tach_id=25   ok, no error.  
Bank Account connection fails always in Pecunia with error message: 
can not load ctapi lib /Applications/Pecunia.app/Contents/pcsc-ctapi-wrapper.dylib - ret=0 response=00 00 (0000)

**Comment by mike-lischke** [comment]
Gefixt.
