### ISSUE TITLE
Pecunia startet nicht mehr bzw. Startseite geht nicht mehr

### ISSUE THREAD

**Issue by adahmen** [pecuniabanking/pecunia-client#370]
Hallo,

Pecunia startet bei mir nicht mehr. Das Pecunia-Fenster geht kurz auf, dann direkt wieder zu. Keine weitere Fehlermeldung.

Vor ein paar Tagen lief noch alles einwandfrei. Wenn ich mich recht erinnere, dann kam dazwischen ein Java-Update, welches ich auch installiert habe. Vielleicht hängt es damit zusammen.

Umfeld: Macbook auf 10.10.1 / Pecunia aktuell aus dem App-Store.

Auf der Konsole finde ich folgende Einträge bei einem Start:
04.12.14 10:53:21,471 Pecunia[486]: BUG in libdispatch client: kevent[EVFILT_VNODE] delete: "Bad file descriptor" - 0x9
04.12.14 10:53:21,472 secinitd[327]: java[487]: unable to get root path for bundle of main executable: /Applications/Pecunia.app/Contents/PlugIns/jre/Contents/Home/bin/java
04.12.14 10:53:24,704 Pecunia[486]: CoreText CopyFontsForRequest received mig IPC error (FFFFFFFFFFFFFECC) from font server
04.12.14 10:53:24,704 Pecunia[486]: CoreText CopyFontsForRequest received mig IPC error (FFFFFFFFFFFFFECC) from font server
04.12.14 10:53:24,744 Pecunia[486]: Pecunia(486,0x7fff7a4b5300) malloc: *** error for object 0x6000000f9900: Invalid pointer dequeued from free list
*** set a breakpoint in malloc_error_break to debug
04.12.14 10:53:24,784 com.apple.xpc.launchd[1]: (de.pecuniabanking.pecunia.89492[486]) Service exited with abnormal code: 102

Ich habe Pecunia auch nochmal gelöscht und frisch installiert ... hat aber auch nicht geholfen.

Was kann ich tun?

VG Albert

**Comment by mike-lischke** [comment]
Das klingt nach einem generellen Fontproblem. Hast du mal gecheckt, ob auf der HD alles ok ist (mit  Disk Utility)? Dann würde ich im Fontbook mal schauen, ob da etwas ungewöhnliches gefunden wird.

**Comment by adahmen** [comment]
Hallo,
ich habe gerade meine Platte geprüft und keinerlei Fehlermeldung bekommen.
Dann habe ich nochmal bei den Fonts geschaut und in der Tat gab es wohl doppelte Fonts ... 
Nachdem ich diese aufgelöst habe gehts nun wieder :-)
DANKE!

VG Albetr
