### ISSUE TITLE
Error-message on adding category

### ISSUE THREAD

**Issue by janstieler** [pecuniabanking/pecunia-client#372]
Hi,
if I want to add a new category I got the error-message „Die Änderungen können nicht zusammengeführt werden.“.
Whats wrong with it? I can't specify the problem with this no saying message.

Greets

**Comment by mike-lischke** [comment]
Da muss vorher noch ein anderes Problem aufgekommen sein. Die Meldung bezieht sich auf das Speichern der Daten und kommt von Core Data. Hast du mal versucht Pecunia neuzustarten?

**Comment by janstieler** [comment]
Hi,
ja habe ich inzwischen mal gemacht. Jetzt taucht die Fehlermeldung nicht mehr auf.
Keine Ahnung was da los war.

Viele Grüße
