### ISSUE TITLE
Verschiedene Fragen

### ISSUE THREAD

**Issue by janstieler** [pecuniabanking/pecunia-client#380]
Hallo,
ich habe ein paar Fragen bzw. Anmerkungen.
Bei mir werden bei manchen Umsätzen keine Kontonummern angezeigt warum ist das so?
Daten aus den Umsätzen kann ich nicht markieren und per Copy and Paste wo anders einfügen. Könnte man das als Funktion eventuell hinzufügen?
Gibt es eine Möglichkeit eigene Icons für die Zuordnungen zu definieren?

Viele Grüße,
Jan Stieler

**Comment by mike-lischke** [comment]
Das sind alles Fragen, die im Forum gestellt werden sollten. Kontonummer werden immer dann angezeigt, wenn verfügbar. Bei Kreditkartenumsätzen gibt es aber keine (zumindest bei der DKB).

Kopieren kann man die einzelnen Daten in der Detailansicht (seit Pecunia 1.2 über die space Taste als Popover zu sehen).

Icons für Zuordnungen. Damit kann ich nichts anfangen. Was ist damit gemeint? (im Forum diskutieren).
Wenn es um Kategorienicons geht, dann kann man diese in den Kategorieneigenschaften ändern (doppelclick, context menu).
