### ISSUE TITLE
AppIcon

### ISSUE THREAD

**Issue by docterd** [pecuniabanking/pecunia-client#383]
i love pecunia but I kinda hate the Icon. I would be very proud to see another icon in future. Here is a suggestion of me

![pecunia](https://cloud.githubusercontent.com/assets/199578/6199769/5cff4354-b458-11e4-9d04-f4bcf590845d.png)

**Comment by mike-lischke** [comment]
Is this an icon you created yourself? Could you deliver a full set of resolutions (16 x 16 up to 256 x 256px)? I actually like the coin icon, but I guess with the advent of Yosemite and more flat things a new icon is due. The € interior is however not perfect as we intend to support several currencies. It's not yet completely implemented, but we intent to add full support. Could you also provide alternatives for the background gradient. I'm not particularly fond of pink and purple like colors.

**Comment by docterd** [comment]
Yes I just created it. I would deliver the asset as SVG or another vector based format. I'm gonna brainstorm some ideas! :-)

**Comment by docterd** [comment]
How about this one

![pecunia2](https://cloud.githubusercontent.com/assets/199578/6200324/afa4d47e-b472-11e4-9fa5-0ef0619f4022.png)

**Comment by mike-lischke** [comment]
Pretty cool. Need to talk with others about that. btw. do you speak german? If you like you can subscribe to our dev mailing list: https://groups.google.com/forum/#!forum/pecunia-banking.

**Comment by heikohaensel** [comment]
Mike, I guess this issue can be closed as the current master got the new App Icon, right?

**Comment by mike-lischke** [comment]
Yep, true. Thanks.
