### ISSUE TITLE
Manuelle Bearbeitung von automatisch verwalteten Konten

### ISSUE THREAD

**Issue by FabianR** [pecuniabanking/pecunia-client#387]
Gibt es eine Möglichkeit automatisch verwaltete Konten manuell zu bearbeiten? 

Konkrete Anwendungsszenarien:

1. Versehentliche Lösung korrigieren:
Ich habe eine automatisch angelegte Buchung versehentlich gelöscht und kann sie derzeit nicht wiederherstellen oder manuell hinzufügen.

2. Ältere Buchungen importieren:
Ich habe ein Konto, das automatisch bis 2013 zurück abgerufen wurde. Jetzt möchte ich meine früheren Buchungen aus einem anderen Programm importieren (zB. als CSV o.ä.). 

BTW: Pecunia ist super :-)
Grüße, Fabian

**Comment by mike-lischke** [comment]
Danke für das Lob :-) Dennoch wäre es uns lieber, wenn solche Fragen im Forum gestellt werden (schon weil dann auch andere an den Antworten partizipieren können). Hast du mal probiert in dieses Konto zu importieren? Im Import Dialog kannst du ja jedes Konto auswählen. Automatische Buchungen sollte eigentlich "von selbst" wieder erscheinen, solange die Bank diese noch vorrätig hat. Bei Buchungen älter als 1 Monat oder so (bankabhängig) wird es aber schwierig. In solchen Fällen empfehle ich sofrt das letzte TM backup der accounts Datei wiederherzustellen.
