### ISSUE TITLE
Pecunia-/Banking API

### ISSUE THREAD

**Issue by osopolar** [pecuniabanking/pecunia-client#389]
Gibt es für Pecunia eine API, so dass andere Programme mit pecunia interagieren können, z.B. Daten auslesen, Überweisungen ausfüllen etc. z.B. [Custom URI Scheme](http://wiki.gnucash.org/wiki/Custom_URI_Scheme) zum erstellen einer Überweisung?

**Comment by mike-lischke** [comment]
Nein. So ein Zugriff ist mit Pecunia nicht möglich.
