### ISSUE TITLE
Syncronisationsabbruch seit MacOSx 10.10

### ISSUE THREAD

**Issue by Alaric84** [pecuniabanking/pecunia-client#390]
Hallo Zusammen,
seit dem update auf Yosemite erhalte ich folgende Fehlernachricht:
Mit 1.1.400 und 1.1.401

<12:01:54.708> HBCI error code: 9010:Nachricht ist komplett nicht bearbeitet (HBMSG=10319)
<12:01:54.712> HBCI error code: 9800:Dialog abgebrochen (HBMSG=10321)
<12:01:54.713> HBCI error code: 9210:Inhaltlich ungültig (HBMSG=10331) (3:4: DialogInit.Idn.sysid=1792153113712230)

Gibt es dazu einen detaillierteren Log?

Grüße
#Alaric

**Comment by foss-** [comment]
Tritt das problem noch mit 1.2 auf? http://pecuniabanking.de/index.php/downloads

**Comment by mike-lischke** [comment]
Merwürdigerweise habe ich diese Meldung auch gelegentlich, ohne einen Grund zu erkennen (DKB via Chipkarte). Beim nächsten Abruf erscheinen die Meldungen dann nicht mehr.

**Comment by Alaric84** [comment]
Ich muss mich korrigieren:
Der Syncronisationsabbruch tritt dann auf, wenn ich den Anmeldename ändere. Die Syncronisation funktioniert nur wenn als Anmeldename die Kontonummer verwendet wird.

Ist das eine bekannte Einschränkung?

**Comment by mike-lischke** [comment]
In welchem Sinn eine Einschränkung? Die Bank legt fest, was zum Login verwendet werden muss und dann muss man es auch so halten.

**Comment by Alaric84** [comment]
Nein - die Bank bietet mir die Möglichkeit meinen Benutzername zu ändern. Damit ist auch eine Anmeldung auf der Banking-Website möglich. Wenn ich diese geänderten Zugangsdaten in Pecunia verwenden will funktioniert das aber nicht - es kommt zum Syncronisationsabbruch. Sobald ich den Anmeldename wieder in die Kontonummer zurück ändere klappt wieder alles. Es hat also nichts mit Yosemite zu tun.

**Comment by mike-lischke** [comment]
Aha, verstehe. Ja, kann sein, dass über HBCI nur die Kontonummer akzeptiert wird. Das ist aber nichts, was Pecunia beeinflussen könnte. Auch das ist eine Festlegung der Bank.

**Comment by foss-** [comment]
Klingt wie notabug.

**Comment by Alaric84** [comment]
hmmm - ok. Ob das jetzt ein Bug ist oder nicht kann ich hier als "USER" nicht beurteilen. Es ist nur völlig undurchsichtig. Änderung des Anmeldenamens ist möglich, aber dann funktioniert HBCI nicht mehr ... 
Ich bin mir als USER also keiner Schuld bewusst. Wenn möglich wäre eine entsprechend aussagekräftige Fehlermeldung super: "Benutzername Passwort Kombination nicht gültig"

Für mich ist der Vorgang hier geschlossen - aber ich denke ich bin nicht der erste und letzte der darauf reingefallen ist.

Danke für eure Unterstützung!

**Comment by foss-** [comment]
Ja, das stimmt sicher. Generell könnte Pecunia bei Probleme bessere Fehlermeldungen zeigen. Aber das ist eine Menge Arbeit und das Entwickler Team halt sehr klein.
