### ISSUE TITLE
Regelwerk-Erweiterung - BETRAG NEGATIV und BETRAG POSITIV als Regel hinzufügen

### ISSUE THREAD

**Issue by BurntWill** [pecuniabanking/pecunia-client#392]
Wäre es möglich ein Feature einzubauen, so dass man bei den REGELN für die KATEGORIEN neben "Verwendungszweck", "Autraggeber", "Auftraggeber-Konto", "Empfänger-Konto" auch noch einen BETRAG angeben könnte. Insbesondere das Kriterum NEGATIVER BETRAG oder POSITIVER BETRAG würden dann Ausgaben und Einnahmen unterschiedlichen Kategorien zuordnen lassen.

Könnt ihr das Regelwerk erweitern um dieses Feature oder ist das ein grosser Aufwand ?

**Comment by mike-lischke** [comment]
Dies und eine ganze Reihe anderer Kriterien sind schon in Pecunia 1.2 enthalten (was noch seiner Veröffentlichung harrt).

![bildschirmfoto 2015-05-20 um 12 46 08](https://cloud.githubusercontent.com/assets/2398704/7724056/5139a02e-feee-11e4-9951-d8d4cba9d1bd.png)

**Comment by BurntWill** [comment]
oha, sehr schön !
