### ISSUE TITLE
Drag-and-drop Kategorisierung ausgefallen

### ISSUE THREAD

**Issue by eugenk** [pecuniabanking/pecunia-client#394]
V1.1.5 (1.1.500) Yosemite 10.10.3

Es geht bei diesem Problem um das "Übersicht" Tab.

Ich kann leider keine Schritte zum Reproduzieren angeben, aber vielleicht habt ihr spontan eine Idee:
Meistens kann ich per drag-and-drop meine Umsätze nicht mehr zu Kategorien hinzufügen. Beim Klicken und Ziehen funktioniert der Ziehen-Teil einfach nicht. Es wird nur der Umsatz markiert, aber nicht gegriffen.

Dieses Verhalten tritt dem Schein nach nichtdeterministisch auf. Hin und wieder funktioniert drag-and-drop, meistens aber nicht. Ganz ohne Änderung von Einstellungen. Einmal funktionierte es nur aus der Umsatzansicht eines Kontos, nicht aber aus der Ansicht aller Konten (oder aller Konten bei der Bank).

**Comment by mike-lischke** [comment]
Show mal im Log (via Hilfemenü), ob da was relevantes drin steht, nachdem du versucht hast einen Eintrag zu ziehen.

**Comment by eugenk** [comment]
Leider passiert im log nichts, wenn ich im UI versuche Umsätze zu ziehen (geöffnet mit `tail -f`).

**Comment by eugenk** [comment]
Wie aus dem Nichts funktioniert drag and drop auf einmal wieder. Konnte die Kategorisierung damit jetzt über einige Programmstarts hinweg benutzen. Ich habe aber nichts an meinem Setup verändert (bis auf `brew upgrade --all`, aber die Packages dürften Pecunia nicht beeinflussen).

Meinetwegen kann dieses issue geschlossen werden.

**Comment by mike-lischke** [comment]
Das ist ja merkwürdig. Aber gut, dass es wieder funktioniert.
