### ISSUE TITLE
NewBankUserController fehlerhaft wenn [[HBCIController controller] addBankUser fehlschlägt

### ISSUE THREAD

**Issue by derpue** [pecuniabanking/pecunia-client#401]
Ich verstehe noch nicht 100% die Intention bzw das korrekte gewünschte Verhalten, deswegen kurz hier als Issue bevor ich es versuchen zu fixen.

Beim Erstellen einer neuen Bankenkennung wird schon im 2. Schritt (nach Eingabe BenutzerID) die Dopplungsprüfung vorgenommen (NewBankUserController.m ab Zeile 164) und danach das der temporäte BankUser in den "richtigen" BankUser gewandelt und danach per `[[HBCIController controller] addBankUser: currentUser];` bei der Bank (nach Passwortanforderung) abgerufen und verknüpft.

Wenn dies klappt, wird NSPanel *userSheet geschlossen und die neue Bankkennung ist angelegt.

Wenn dies nicht klappt (z.B. Passwort ist vertippt) wird die "3. Seite" mit den ganzen Details wie BankURL, HBCI Version und Co angezeigt. Wenn ich dann da auf weiter gehe kommt der Fehler dass die Bankkennung bereits angelegt wurde (klar der temp BankUser wurde schon in einen richtigen BankUser "umkopiert"), da die Prüfung auf Doppelte Kennung erneut durchgeführt wird.

Mangels (noch) nicht vorhandenen tieferen Verständnisses des Codes hier kurz die Fragen:

Wie ist das gewünschte Verhalten bzgl. der Seiten? Sollte die 3. Seite immer angezeigt werden (wird wohl den Fix einfacher machen) und erst danach der temp in einen richtigen kopiert werden? Oder sollte die 3. Seite wie jetzt nur wenn was klemmt angezeigt werden?
Kann `[[HBCIController controller] addBankUser: currentUser];` auch mit dem temp BankUser aufgerufen werden, sodass wir erst bei Erfolg den echten erstellen? (Ich denke hier an abhängigen Objekten die dann evtl. im falschen Context erstellt werden, wobei es für mich im ersten Moment so aussieht als wenn addBankUser da nichts dergleichen anstellt)

Danke

**Comment by mike-lischke** [comment]
Ja, ich hab da auch ein ungutes Gefühl, den Temp User dafür zu verwenden. U.a. werden von diesem Objekt andere Objekte verwaltet (Konten z.B.). Eine bessere Idee ist vermutlich im Fehlerfall den gerade hinzugefügten Nutzer wieder zu löschen (es gibt ein deleteUser:) und den temporären Nutzer wieder einzusetzen (also currentUser merken, bis alles ok ist). Beim nächsten Schritt wird ja dann wieder versucht, den neuen Nutzer hinzuzufügen. Das sollte dann also funktionieren.

**Comment by derpue** [comment]
Mit einem Child-Context sollte es dennoch klappen. Bei Erfolg den Child-MOC speichern und die Objekte darin "rutschen" automatisch in den Haupt-MOC (Zumindest laut Google) 
Ich schau mal ob morgen Zeit ist, dass mal zu bauen.

Ein anderer Punkt, obwohl fast eigener Issue: 
Im Moment wird die Dublettenprüfung nach der Benutzerkennung (BankUser.userId) gemacht.
Zugegeben sehr unwahrscheinlicher Fall, aber was ist wenn ich die selbe Kennung bei 2 verschiedenen Banken habe? Sollte die Doublettenprüfung nicht die Kombination BenutzerKennung BLZ sein? (Das JavaBackend legt die Passports auch in Form BLZ_Kennung.dat an)

**Comment by mike-lischke** [comment]
Hmm, aber extra dafür einen eigenen MOC anzulegen finde ich jetzt aber auch übertrieben, wenn man eigentlich nur ein paar wenige Schritte machen muss, wie oben beschrieben.

Für das andere Problem leg' bitte einen eigenen Issue an oder, wenn es Sinn macht zu diskutieren, komm auf die Entwicklermailingliste. Der issue tracker ist nicht der richtige Platz dafür.

**Comment by derpue** [comment]
Alles klar, dieses Problem ist mit https://github.com/pecuniabanking/pecunia-client/commit/9c296e7b41450435300d464041b2cc68eadbf9a8 erledigt
