### ISSUE TITLE
Anlegen eines ING DiBa Kontos das angeblich bereits existiert nicht möglich

### ISSUE THREAD

**Issue by barthnet** [pecuniabanking/pecunia-client#402]
Beim Hinzufügen einer weiteren Bankenkennung der ING DiBa (BLZ: 50010517) taucht nach Eingabe der Benutzerkennung der erste Fehler auf:

HBCI-Fehler aufgetreten!
Hostname/IP-Adresse darf nicht leer sein

Anschließend erscheint die Fehlermeldung:

Bankkennung existiert bereits
Eine Bankkennung mit der Benutzerkennung xxxxxxxxxx existiert bereits. Bitte löschen Sie zuerst die alte Bankkennung.

Dabei ist es völlig egal welche Kontonummer eingetragen wird. Alle Eingaben "existierten bereits". 

----- System -----
Mac OS X 10.10.3
Pecunia 1.2.0 (1.2.0)

**Comment by mike-lischke** [comment]
Duplikat von #401
