### ISSUE TITLE
Auftraggeber und Verwendungszwecke in Detailansicht nicht kopierbar

### ISSUE THREAD

**Issue by doits** [pecuniabanking/pecunia-client#406]
In der Detailansicht (per `Space` bei einer Buchung) sind der Auftraggeber und Verwendungszweck seit Pecunia 1.2 nicht mehr auswählbar und damit nicht mehr kopierbar. (Lediglich IBAN, BIC und der Wert sind es.)

Es wäre schön, wenn auch die o.g. Details bzw. alles Texte in diesem Dialog anwählbar und kopierbar wären.

**Comment by ogun-** [comment]
Dieses Feature vermisse ich auch. Ist für mich sehr wichtig, das im Verwendungszweck oft Referenzen stehen die ich brauche um die Buchung zu zuweisen. Seit 1.2 muss ich die abtippen.

**Comment by mike-lischke** [comment]
Fixed in 287678bb600838f51eac3f8a82d3e0acd8eb6874
