### ISSUE TITLE
Vorlagen-Erstellung: Programmabsturz

### ISSUE THREAD

**Issue by Alicia33** [pecuniabanking/pecunia-client#408]
Pecunia 1.2 unter 10.9.5:

Beim Vorlagenerstellen aus einer Buchung in der Übersicht stürzt das Programm ab.

24.06.15 11:09:37,208 com.apple.launchd.peruser.501[262]: (de.pecuniabanking.pecunia.305392[2677]) Exited with code: 102

**Comment by mike-lischke** [comment]
Alicia, hat sich dieses Problem erledigt?

**Comment by Alicia33** [comment]
Hallo Mike,

ja das Problem ist seit längerem gelöst. Thx
