### ISSUE TITLE
Expenses not visible anymore - Ausgaben nicht mehr sichtbar

### ISSUE THREAD

**Issue by janisHD** [pecuniabanking/pecunia-client#412]
I'm on version 1.1.5 with MacOSX 10.10.4. Today I opened pecunia and in the 'Overview' section in the 'Categories' view, only the income and the self defined accounts are visible, the default expense accounts are not displayed. Is it possible that they are only made invisible (couldn't find any setting that could correspond to such a result) and is ist possible to newly generate them (the default expense accounts)?

**Comment by mike-lischke** [comment]
Is this about the categories part of the tree? The default categories can automatically be created by removing all existing ones (not the accounts, just the categories).
