### ISSUE TITLE
Any chance of/plans for a Linux/BSD client?

### ISSUE THREAD

**Issue by sixtyfive** [pecuniabanking/pecunia-client#414]
As it stands, Pecunia seems to be the most featureful, nice-looking and sensible FOSS banking software on the planet, with alternatives such as GnuCash+plugin not being real alternatives at all. Are there any plans at all to produce a GUI (Qt, whatever) for the Pecunia backend that would run on a wider range of operating systems?

**Comment by mike-lischke** [comment]
Thanks for your kind words, but I'm afraid we cannot help much here. One important point of Pecunia's charme is that it runs natively on OSX. This is more than just the UI, but e.g. proper use of security support by the OS (which is imporant for an app like this) up to persistency. It would be major rewrite to port this to cross platofrm UI (and usually it looks much worse after that).

**Comment by sixtyfive** [comment]
Indeed, beautiful multiplatform-software is still an elusive beast. But then, just a couple of years ago, multiplatform-software, beautiful or not, was still an elusive beast, so here's hoping for a good future. Thanks for the reply though :)
