### ISSUE TITLE
Absturz & nicht mehr verwendbar nach Groß-/Kleinschreibung

### ISSUE THREAD

**Issue by Muster7** [pecuniabanking/pecunia-client#415]
Ich habe auf OS X 10.9.5 bzw. 10.8.? jeweils frisch Pecunia 1.2 installiert und mein Konto eingetragen. Abgesehen davon, dass wie [in Issue 404](https://github.com/pecuniabanking/pecunia-client/issues/404) von jemandem bereits beschrieben verschiedene Tabs zu Abstürzen des Programms führen, habe ich gerade auf beiden Rechnern versucht, die automatische Groß-/Kleinschreibung zu aktivieren.

Nach der Warnung, dass da jetzt etwas heruntergeladen werden muss, stürzt Pecunia ab. Und anschließend kann man es auch nicht mehr öffnen (der Icon springt kurz auf und ab, dann verschwindet er wieder). In der Konsole werden folgende Fehler gemeldet:

```
12.08.15 23:39:40,591 Pecunia[7467]: Invalid color System, labelColor (warning given only once)
12.08.15 23:39:41,300 com.apple.launchd.peruser.502[270]: (de.pecuniabanking.pecunia.86624[7467]) Exited with code: 102
```

Was kann ich tun? Und wie komme ich wieder an Pecunia und meine Kontodaten ran? Backups etc habe ich nicht, weil ich das Programm gerade erst zwei Stunden installiert habe, aber in der Zeit eben alles kategorisiert etc habe.

**Comment by mike-lischke** [comment]
Auf 10.8 läuft Pecunia 1.2+ nicht. Bleibt also nur 10.9. Die Warnung über eine unbekannte Farbe ist nur das, eine Warnung. Die führt nicht zum crash.

Pecunia hat noch ein eigenes Log im Pfad: /Users/<user>/Library/Containers/de.pecuniabanking.pecunia/Data/Library/Logs/Pecunia/. Schau dort mal ob es weitere Hinweise auf das Problem gibt. Bei jedem Start wird ein neues Logfile erstellt und die anderen rotiert.

**Comment by Muster7** [comment]
Stimmt, der andere Rechner hat ebenfalls 10.9.5. Hier ist das letzte Log, ich verstehe sowas leider nicht:

```
2015/08/13 00:06:29:393  [Info] Starting up application
2015/08/13 00:06:29:394  [Info] Arguments: (
    "/Applications/Pecunia.app/Contents/MacOS/Pecunia"
)
2015/08/13 00:06:29:394  [Info] Pecunia version: 1.2.0
2015/08/13 00:06:29:395  [Info] Machine + OS: MacBookPro8,1, Version 10.9.5 (Build 13F1096)
2015/08/13 00:06:29:395  [Info] Mem size: 10.0GB
2015/08/13 00:06:29:395  [Info] CPU : Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz
2015/08/13 00:06:29:395  [Info] Process environment: {
    "APP_SANDBOX_CONTAINER_ID" = "de.pecuniabanking.pecunia";
    "Apple_PubSub_Socket_Render" = "/tmp/launch-nMuDIG/Render";
    "CFFIXED_USER_HOME" = "/Users/Horst/Library/Containers/de.pecuniabanking.pecunia/Data";
    HOME = "/Users/Horst/Library/Containers/de.pecuniabanking.pecunia/Data";
    LOGNAME = Horst;
    PATH = "/usr/bin:/bin:/usr/sbin:/sbin";
    SHELL = "/bin/zsh";
    "SSH_AUTH_SOCK" = "/tmp/launch-KKuOVC/Listeners";
    TMPDIR = "/var/folders/d8/qq47_6m50glbx_sq6k122w2m0000gp/T/de.pecuniabanking.pecunia/";
    USER = Horst;
    "__CF_USER_TEXT_ENCODING" = "0x1F6:0:3";
    "__CHECKFIX1436934" = 1;
}
2015/08/13 00:06:29:448  [Info] Data dir URL: file:///Volumes/Documents/
2015/08/13 00:06:29:448  [Info] Pecunia file URL: file:///Volumes/Documents/Pecunia-Datenbank.pecuniadata/
2015/08/13 00:06:29:448  [Info] Passport dir: /Users/Horst/Library/Containers/de.pecuniabanking.pecunia/Data/Library/Application Support/Pecunia/Passports
2015/08/13 00:06:29:448  [Info] Import/Export dir: /Users/Horst/Library/Containers/de.pecuniabanking.pecunia/Data/Library/Application Support/Pecunia/ImportSettings
2015/08/13 00:06:29:448  [Info] Temp dir: /var/folders/d8/qq47_6m50glbx_sq6k122w2m0000gp/T/de.pecuniabanking.pecunia/
2015/08/13 00:06:30:145  [Error] Caught signal 4
2015/08/13 00:06:30:146  [Error] 0   Pecunia                             0x000000010315f333 Pecunia + 230195
2015/08/13 00:06:30:146  [Error] 1   Pecunia                             0x0000000103140539 Pecunia + 103737
2015/08/13 00:06:30:146  [Error] 2   libsystem_platform.dylib            0x00007fff87a6b5aa _sigtramp + 26
2015/08/13 00:06:30:146  [Error] 3   libswiftCore.dylib                  0x000000010375a380 _TMdCSs17NonObjectiveCBase + 16
2015/08/13 00:06:30:146  [Error] 4   Pecunia                             0x00000001032faf3a Pecunia + 1916730
2015/08/13 00:06:30:146  [Error] 5   Pecunia                             0x0000000103129b51 Pecunia + 11089
2015/08/13 00:06:30:146  [Error] 6   CoreFoundation                      0x00007fff8f0f0309 -[NSSet makeObjectsPerformSelector:] + 201
2015/08/13 00:06:30:146  [Error] 7   AppKit                              0x00007fff89201afd -[NSIBObjectData nibInstantiateWithOwner:topLevelObjects:] + 1157
2015/08/13 00:06:30:146  [Error] 8   AppKit                              0x00007fff891f65ce loadNib + 327
2015/08/13 00:06:30:146  [Error] 9   AppKit                              0x00007fff891f5b6c +[NSBundle(NSNibLoading) _loadNibFile:nameTable:withZone:ownerBundle:] + 288
2015/08/13 00:06:30:146  [Error] 10  AppKit                              0x00007fff891f595c -[NSBundle(NSNibLoading) loadNibNamed:owner:topLevelObjects:] + 197
2015/08/13 00:06:30:147  [Error] 11  AppKit                              0x00007fff891f574b +[NSBundle(NSNibLoading) loadNibNamed:owner:] + 357
2015/08/13 00:06:30:147  [Error] 12  AppKit                              0x00007fff891f1597 NSApplicationMain + 448
2015/08/13 00:06:30:147  [Error] 13  libdyld.dylib                       0x00007fff8ce5a5fd start + 1
2015/08/13 00:06:30:147  [Error] 14  ???                                 0x0000000000000001 0x0 + 1
2015/08/13 00:06:30:147  [Error] Failed to save context. Reason: (null)
 ```

**Comment by Muster7** [comment]
Irgendeine Idee, wie ich wieder Pecunia benutzen kann?

**Comment by mike-lischke** [comment]
Wenn es kein backup gibt, dann hilft wohl nur noch einmal von vorn anzufangen. Einfach die accounts.pecuniadata umbennen und Pecunia legt sie neu an, beim nächsten Start. Vielleicht auch erstmal alles am Originalplatz belassen. Ich hoffe //Volumes/Documents ist kein Netzwerklaufwerk.

**Comment by Muster7** [comment]
Ist das die Datei, deren Speicherort man selbst festlegen konnte? Dann hilft umbenennen (oder löschen) nichts, Pecunia öffnet sich trotzdem nicht (bzw. stürzt sofort wieder ohne Meldung ab). Es ist auch kein Netzwerklaufwerk gewesen.

**Comment by mike-lischke** [comment]
Hmm, dann bliebe nur noch die Settings zurück zu setzen (Entsorgung von de.pecuniabanking.pecunia.plist). Müsste sich in ~/Library/Containers/de.pecuniabanking.pecunia/Data/Library/Preferences befinden. Es kann auch gleich der gesamte Pecunia folder verschwinden. Wenn das Problem von der Groß/Kleinschreibung stammt, sollte es damit getan sein.

Diese automatische Anzeige benötigt eine Wordliste, die zunächst heruntergeladen und in die Datenbank übernommen werden muss. Könnte sein, dass dieser Vorgang in der Sandbox Probleme bereitet.

**Comment by Muster7** [comment]
Vielen Dank, nach dem Löschen von de.pecuniabanking.pecunia.plist unter deiner Pfadangabe ging es. Die Groß-/Kleinschreibung fasse ich jetzt nicht mehr an ... es sei denn, ich kann damit irgendwie bei der Fehlersuche behilflich sein?

**Comment by Muster7** [comment]
Na gut, ein Problem kann ich nachschieben: Ich kann Pecunia nicht beibringen, meine vorhandene Datenbank zu verwenden. Wenn ich sie per Doppelklick im Finder öffne, geht es problemlos. Aber sobald ich unter Einstellungen > Speicherort > Verwenden die Änderung vornehmen möchte, stürzt Pecunia ab und öffnet sich gleich wieder, abermals ohne neue Datenbank. In der Konsole finde ich folgende Fehlermeldung:

```
18.08.15 09:38:51,154 com.apple.appkit.xpc.openAndSavePanelService[4895]: ERROR: CGSSetWindowTransformAtPlacement() returned 1001
18.08.15 09:38:51,174 com.apple.appkit.xpc.openAndSavePanelService[4895]: ERROR: CGSSetWindowTransformAtPlacement() returned 1001
18.08.15 09:38:51,191 com.apple.appkit.xpc.openAndSavePanelService[4895]: ERROR: CGSSetWindowTransformAtPlacement() returned 1001
18.08.15 09:38:51,205 com.apple.appkit.xpc.openAndSavePanelService[4895]: ERROR: CGSSetWindowTransformAtPlacement() returned 1001
18.08.15 09:38:51,222 com.apple.appkit.xpc.openAndSavePanelService[4895]: ERROR: CGSSetWindowTransformAtPlacement() returned 1001
18.08.15 09:38:51,238 com.apple.appkit.xpc.openAndSavePanelService[4895]: ERROR: CGSSetWindowTransformAtPlacement() returned 1001
18.08.15 09:38:51,255 com.apple.appkit.xpc.openAndSavePanelService[4895]: ERROR: CGSSetWindowTransformAtPlacement() returned 1001
18.08.15 09:38:51,272 com.apple.appkit.xpc.openAndSavePanelService[4895]: ERROR: CGSSetWindowTransformAtPlacement() returned 1001
18.08.15 09:38:51,289 com.apple.appkit.xpc.openAndSavePanelService[4895]: ERROR: CGSSetWindowTransformAtPlacement() returned 1001
18.08.15 09:38:51,305 com.apple.appkit.xpc.openAndSavePanelService[4895]: ERROR: CGSSetWindowTransformAtPlacement() returned 1001
18.08.15 09:38:51,321 com.apple.appkit.xpc.openAndSavePanelService[4895]: ERROR: CGSSetWindowTransformAtPlacement() returned 1001
18.08.15 09:38:51,339 com.apple.appkit.xpc.openAndSavePanelService[4895]: ERROR: CGSSetWindowTransformAtPlacement() returned 1001
18.08.15 09:38:51,355 com.apple.appkit.xpc.openAndSavePanelService[4895]: ERROR: CGSSetWindowTransformAtPlacement() returned 1001
18.08.15 09:38:51,355 com.apple.appkit.xpc.openAndSavePanelService[4895]: ERROR: CGSSetWindowTransformAtPlacement() returned 1001
18.08.15 09:38:57,611 com.apple.appkit.xpc.openAndSavePanelService[4895]: PSsetwindowlevel, error setting window level (1001)
18.08.15 09:38:57,961 Pecunia[4896]: Invalid color System, labelColor (warning given only once)
18.08.15 09:38:58,768 Pecunia[4896]: CoreText CopyFontsForRequest received mig IPC error (FFFFFFFFFFFFFECC) from font server
18.08.15 09:38:58,768 Pecunia[4896]: CoreText CopyFontsForRequest received mig IPC error (FFFFFFFFFFFFFECC) from font server
```

**Comment by mike-lischke** [comment]
Hat sich in der Zwischenzeit die Situation gebessert (insbesondere mit dem 1.2.1 update)?

**Comment by Muster7** [comment]
Beide Probleme (Groß-/Kleinschreibung und Abstürze bei bestimmten Tabs) sind verschwunden. Die Groß-/Kleinschreibung scheint zu funktionieren, allerdings kann ich Pecunia nicht normal beenden. Seit 12 Stunden (nach dem Download der Wörterbuchdateien) heißt es "Beenden nicht möglich - Pecunia kann im Moment nicht beendet werden da noch Daten aktualisiert werden. Bitte versuchen Sie es später noch einmal." Über Sofort beenden geht das dann natürlich, und hat auch keine weiteren Probleme ergeben.

Kann man eigentlich die Wörterbücher selbst erweitern?

**Comment by mike-lischke** [comment]
Ausgezeichnet. Danke für das Feedback. Warum allerdings der fertige Download nicht angezeigt wird (weshalb Pecunia sich weigert zu beenden) verstehe ich nicht. Ich hab das in letzter Zeit mehrfach durchexzerziert und keine Probleme gesehen.

Prinzipiell könnte man das Wörterbuch erweitern. Dazu müsste man direkt in der SQLite DB arbeiten. Aber, zum einen ist das nicht unbedingt komfortabel und zum anderen werden alle Änderungen verworfen, wenn es mal ein Update der Wortliste gibt. Ich überlege schon an einer Verbesserung, aber die Umsetzung wird dauern.
