### ISSUE TITLE
Holen von DKB Umsätzen nicht möglich

### ISSUE THREAD

**Issue by JHoahg** [pecuniabanking/pecunia-client#416]

**Comment by noetig** [comment]
Ich habe die selben Probleme. Das Problem existiert bereits seit einigen Tagen.
Same problem here. Problem exist already for few days.

**Comment by mike-lischke** [comment]
Ich vermute die DKB hat mal wieder etwas an ihrer Internetseite verändert, was unser screen scraping stört. Wird ein bischen dauern.

**Comment by tmerten** [comment]
Funktionierende version:
http://www.pecuniabanking.de/downloads/1.0/support/PecuniaSupport12.dmg
(via http://www.onlinebanking-forum.de/forum/topic.php?t=19252 )

**Comment by JHoahg** [comment]
Danke!
