### ISSUE TITLE
SEPA-Überweisung: Absturz bei leerer IBAN

### ISSUE THREAD

**Issue by davidak** [pecuniabanking/pecunia-client#417]
Schritte zum reproduzieren:

1. Pecunia öffnen
2. Überweisungen
3. neue SEPA-Überweisung erstellen
4. ins Feld IBAN klicken
5. in ein anderes Feld klicken, z.B. Empfänger, BIC, Betrag
6. ???
7. Profit

**Comment by heikohaensel** [comment]
Im aktuellen Entwicklungsstand der Version 1.3 kann ich das nicht mehr nachvollziehen. Wenn ich nach dem Feld IBAN in eines der anderen Felder klicke, dann wechselt der Fokus auf das entsprechende Feld ohne das etwas abstürzt.

**Comment by mike-lischke** [comment]
Danke. Eigentlich wollte ich das changeset hier verlinken, aber ehe ich das jetzt finde...
