### ISSUE TITLE
Gesuchte Umsätze sind nicht editierbar 

### ISSUE THREAD

**Issue by ogun-** [pecuniabanking/pecunia-client#420]
Wenn man eine Umsatzsuche startet und dann 'Verwendungszweck und Notizen' eines gefundenen Umsatzes editieren will, verliert das Eingabefeld den Focus.
Ich benutze Version 1.1.5

Ein gesuchter und ein ausgewählter Umsatz:
![image](https://cloud.githubusercontent.com/assets/998491/10389934/74a86990-6e75-11e5-94c0-29f8deb54edd.png)

Zustand nachdem man den ersten Buchstaben eingegeben hat:
![image](https://cloud.githubusercontent.com/assets/998491/10389968/b621481a-6e75-11e5-98ac-4a2a1cd0f0d9.png)

Danke für das tolle Programm!

**Comment by mike-lischke** [comment]
Das werden wir nicht mehr bereinigen, da in der neuen 1.2er Version diese Detailinformation über ein neues Panel angezeigt werden.

![bildschirmfoto 2015-10-10 um 11 06 45](https://cloud.githubusercontent.com/assets/2398704/10410335/2dff793c-6f3f-11e5-8f9e-3b027f150cb9.png)
