### ISSUE TITLE
Support for number26.de account

### ISSUE THREAD

**Issue by osopolar** [pecuniabanking/pecunia-client#422]
Hi, I recently got a bank account from [number 26](https://number26.de/), but the is no support for Pecunia, as they don't and won't use HCBI. At least I'd like to get the transactions from there imported into Pecunia. Currently I add transactions by hand, but that's not very comfortable. How else could I get the data imported into Pecunia?

1. Import via CSV: Their support toled me, that they do not offer csv export yet. If there is more demand for that feature, they may add it – so if anybody else is interested in that, please send a request to support@number26.de
2. Parsing their website/App, as it is done for example for DKB-Visa. This could be implemented for Pecunia, but if the website changes the code needs to be updated too.

Is there any other way to get data into Pecunia, for example provided as JSON string? Anyway, currently it doesn't seem that number26 is interested in supporting other apps. Hopefully this changes if there is more demand.

**Comment by mike-lischke** [comment]
There is no other way. But using screen scraping is quite reliable. It's very often used and sites don't change that often. For instance in Hibiscus there are many such scripts.

However, if you want to have this in you have to implement it yourself (the plugin structure is there).
