### ISSUE TITLE
Fehlende Anzeige im Verlauf

### ISSUE THREAD

**Issue by JHoahg** [pecuniabanking/pecunia-client#424]
OS:el captain.
hallo,
seit dem update auf el captain, werden keine zahlen mehr in der schwarzen box im verlauf angezeigt, die erscheint, wenn man mit dem mauszeiger über die balken fährt.

**Comment by mike-lischke** [comment]
Hi, schon mal ein Update über den AppStore versucht?

**Comment by JHoahg** [comment]
moin,
mein installiertes pecunia sagt es sei version 1.2.08, die version aus dem
appstore ist ja "nur" 1.1.6. ich habe nochmal versucht die app store  
version zu installieren, hat aber leider geklappt(pecunia sagt immer noch  
es wäre 1.2.08).
-johannes

Am 14.11.2015, 20:04 Uhr, schrieb Mike Lischke <notifications@github.com>:

**Comment by mike-lischke** [comment]
Aha, ich wusste nicht, dass du schon auf der 1.2 bist. Dann hole dir doch mal von der Pecunia Homepage ein Update.

**Comment by JHoahg** [comment]
hi,
die version auf der website ist 1.2.08. ich habs nochmal neuinstalliert,  
der fehler besteht aber leider immer noch.
die achsenbeschriftung an den plots ist auch kaputt, d.h. nicht vorhanden.

-johannes


Am 16.11.2015, 17:06 Uhr, schrieb Mike Lischke <notifications@github.com>:

**Comment by mike-lischke** [comment]
Oh, ich dachte, der Fix wäre schon drin. Im Code ist es jedenfalls schon korrigiert. Müsste dann hoffentlich beim nächsten release build mit dabei sein.

**Comment by webflo** [comment]
Ich habe das gleiche Problem. Gibt es schon ein Termin für das nächste Release oder wie kann man die App selbst bauen? Danke!

**Comment by mike-lischke** [comment]
Selbst bauen ist einfach: Sourcen von Github holen, Projekt in XCode öffnen, bauen, fertig.

**Comment by webflo** [comment]
Danke funktioniert wieder.
