### ISSUE TITLE
1.2.1 (App Store) stürzt direkt nach Start ab

### ISSUE THREAD

**Issue by Debilski** [pecuniabanking/pecunia-client#434]
Nach dem Upgrade auf 1.2.1 bekomme ich ein Fenster mit „Datenmigration Die Verwendungszweckinformationen werden nach SEPA-Informationen durchsucht. Dies kann bei großen Datenmengen etwas länger dauern.“ und wenn ich dort auf OK klicke, stürze das Programm sofort ab.

Kommandozeile:

    $ /Applications/Pecunia.app/Contents/MacOS/Pecunia
    HBCI Server up and running...
    2016-01-23 10:41:57.200 Pecunia[4802:294430] CoreData: Failed to load optimized model at path '/Applications/Pecunia.app/Contents/Resources/Accounts.momd/Accounts 15.omo'

Spindump (zumindest der Anfang):

    Date/Time:       2016-01-23 10:42:54 +0100
    OS Version:      Mac OS X 10.11.4 (Build 15E27e)
    Architecture:    x86_64h
    Report Version:  22

    Command:         Pecunia
    Path:            /Applications/Pecunia.app/Contents/MacOS/Pecunia
    Version:         1.2.1 (1.2.104)
    App Item ID:     581402740
    App External ID: 815952598
    Parent:          fish [2321]
    Responsible:     Terminal [1910]
    PID:             4802

    Event:           spin
    Duration:        2.10s (process was unresponsive for 2 seconds before sampling)
    Steps:           21 (100ms sampling interval)

    Hardware model:  MacBookPro11,5
    Active cpus:     8

    Fan speed:       2161 rpm

    --------------------------------------------------
    Timeline format: stacks are sorted chronologically
    Use -i and -heavy to re-report with count sorting
    --------------------------------------------------

    Heaviest stack for the main thread of the target process:
      21  start + 1 (libdyld.dylib + 13741) [0x7fff80f105ad]
      21  NSApplicationMain + 1176 (AppKit + 29052) [0x7fff92df317c]
      21  -[NSApplication run] + 682 (AppKit + 252820) [0x7fff92e29b94]
      21  -[NSApplication _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 454 (AppKit + 299066) [0x7fff92e3503a]
      21  _DPSNextEvent + 2245 (AppKit + 303268) [0x7fff92e360a4]
      21  AEProcessAppleEvent + 55 (HIToolbox + 264953) [0x7fff8457baf9]
      21  aeProcessAppleEvent + 288 (AE + 32516) [0x7fff8eeb1f04]
      21  dispatchEventAndSendReply(AEDesc const*, AEDesc*) + 31 (AE + 32744) [0x7fff8eeb1fe8]
      21  aeDispatchAppleEvent(AEDesc const*, AEDesc*, unsigned int, unsigned char*) + 531 (AE + 33377) [0x7fff8eeb2261]
      21  _NSAppleEventManagerGenericHandler + 102 (Foundation + 349351) [0x7fff88b304a7]
      21  -[NSAppleEventManager dispatchRawAppleEvent:withRawReply:handlerRefCon:] + 290 (Foundation + 349741) [0x7fff88b3062d]
      21  -[NSApplication(NSAppleEventHandling) _handleCoreEvent:withReplyEvent:] + 250 (AppKit + 321111) [0x7fff92e3a657]
      21  -[NSApplication(NSAppleEventHandling) _handleAEOpenEvent:] + 557 (AppKit + 322477) [0x7fff92e3abad]
      21  -[NSApplication _sendFinishLaunchingNotification] + 203 (AppKit + 1654423) [0x7fff92f7fe97]
      21  -[NSApplication _postDidFinishNotification] + 297 (AppKit + 1655085) [0x7fff92f8012d]
      21  -[NSNotificationCenter postNotificationName:object:userInfo:] + 66 (Foundation + 28634) [0x7fff88ae1fda]
      21  _CFXNotificationPost + 693 (CoreFoundation + 380821) [0x7fff8b4f8f95]
      21  -[_CFXNotificationRegistrar find:object:observer:enumerator:] + 1922 (CoreFoundation + 384322) [0x7fff8b4f9d42]
      21  ___CFXNotificationPost_block_invoke + 50 (CoreFoundation + 659346) [0x7fff8b53cf92]
      21  _CFXRegistrationPost + 407 (CoreFoundation + 660007) [0x7fff8b53d227]
      21  ___CFXRegistrationPost_block_invoke + 63 (CoreFoundation + 660143) [0x7fff8b53d2af]
      21  __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 12 (CoreFoundation + 660252) [0x7fff8b53d31c]
      21  ??? (Pecunia + 82600) [0x105fcd2a8]
      21  ??? (Pecunia + 102334) [0x105fd1fbe]
      21  ??? (Pecunia + 126942) [0x105fd7fde]
      21  objc_msgSend + 209 (libobjc.A.dylib + 5521) [0x7fff91708591]
      21  lookUpImpOrForward + 179 (libobjc.A.dylib + 27912) [0x7fff9170dd08]
      21  _class_initialize + 711 (libobjc.A.dylib + 29640) [0x7fff9170e3c8]
      21  ??? (Pecunia + 1620351) [0x10614497f]
      18  ??? (Pecunia + 1631649) [0x1061475a1]
      18  -[NSBundle classNamed:] + 85 (Foundation + 482713) [0x7fff88b50d99]
      18  +[NSBundle bundleForClass:] + 70 (Foundation + 87588) [0x7fff88af0624]
      18  class_respondsToSelector + 37 (libobjc.A.dylib + 44986) [0x7fff91711fba]
      18  lookUpImpOrNil + 20 (libobjc.A.dylib + 36239) [0x7fff9170fd8f]
      18  lookUpImpOrForward + 364 (libobjc.A.dylib + 28097) [0x7fff9170ddc1]
      18  _class_resolveMethod + 124 (libobjc.A.dylib + 42171) [0x7fff917114bb]
      18  objc_msgSend + 209 (libobjc.A.dylib + 5521) [0x7fff91708591]
      18  lookUpImpOrForward + 179 (libobjc.A.dylib + 27912) [0x7fff9170dd08]
      18  _class_initialize + 711 (libobjc.A.dylib + 29640) [0x7fff9170e3c8]
      18  ??? (Pecunia + 1482665) [0x106122fa9]
      3   ??? (Pecunia + 1524672) [0x10612d3c0]
      1   ??? (<5C6DC4CB-402D-3BDD-8CEE-DDCFA60B1D79> + 1568934) [0x10663c0a6]
      1   ??? (<5C6DC4CB-402D-3BDD-8CEE-DDCFA60B1D79> + 1355832) [0x106608038] (running)

    Process:         Pecunia [4802]
    Path:            /Applications/Pecunia.app/Contents/MacOS/Pecunia
    Architecture:    x86_64
    Parent:          fish [2321]
    Responsible:     Terminal [1910]
    UID:             501
    Task size:       28960 pages (+1562)
    CPU Time:        1.997s
    Note:            Unresponsive for 2 seconds before sampling
    Note:            7 idle work queue threads omitted

      Thread 0x47e1e          DispatchQueue 1         21 samples (1-21)       priority 46 (base 46)   cpu time 1.997s
      <thread QoS user interactive (requested user interactive), process unclamped, process received importance donation from WindowServer [183], IO policy important>
      21  start + 1 (libdyld.dylib + 13741) [0x7fff80f105ad] 1-21
        21  NSApplicationMain + 1176 (AppKit + 29052) [0x7fff92df317c] 1-21
          21  -[NSApplication run] + 682 (AppKit + 252820) [0x7fff92e29b94] 1-21
            21  -[NSApplication _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 454 (AppKit + 299066) [0x7fff92e3503a] 1-21
              21  _DPSNextEvent + 2245 (AppKit + 303268) [0x7fff92e360a4] 1-21
                21  AEProcessAppleEvent + 55 (HIToolbox + 264953) [0x7fff8457baf9] 1-21
                  21  aeProcessAppleEvent + 288 (AE + 32516) [0x7fff8eeb1f04] 1-21
                    21  dispatchEventAndSendReply(AEDesc const*, AEDesc*) + 31 (AE + 32744) [0x7fff8eeb1fe8] 1-21
                      21  aeDispatchAppleEvent(AEDesc const*, AEDesc*, unsigned int, unsigned char*) + 531 (AE + 33377) [0x7fff8eeb2261] 1-21
                        21  _NSAppleEventManagerGenericHandler + 102 (Foundation + 349351) [0x7fff88b304a7] 1-21
                          21  -[NSAppleEventManager dispatchRawAppleEvent:withRawReply:handlerRefCon:] + 290 (Foundation + 349741) [0x7fff88b3062d] 1-21
                            21  -[NSApplication(NSAppleEventHandling) _handleCoreEvent:withReplyEvent:] + 250 (AppKit + 321111) [0x7fff92e3a657] 1-21
                              21  -[NSApplication(NSAppleEventHandling) _handleAEOpenEvent:] + 557 (AppKit + 322477) [0x7fff92e3abad] 1-21
                                21  -[NSApplication _sendFinishLaunchingNotification] + 203 (AppKit + 1654423) [0x7fff92f7fe97] 1-21
                                  21  -[NSApplication _postDidFinishNotification] + 297 (AppKit + 1655085) [0x7fff92f8012d] 1-21
                                    21  -[NSNotificationCenter postNotificationName:object:userInfo:] + 66 (Foundation + 28634) [0x7fff88ae1fda] 1-21
                                      21  _CFXNotificationPost + 693 (CoreFoundation + 380821) [0x7fff8b4f8f95] 1-21
                                        21  -[_CFXNotificationRegistrar find:object:observer:enumerator:] + 1922 (CoreFoundation + 384322) [0x7fff8b4f9d42] 1-21
                                          21  ___CFXNotificationPost_block_invoke + 50 (CoreFoundation + 659346) [0x7fff8b53cf92] 1-21
                                            21  _CFXRegistrationPost + 407 (CoreFoundation + 660007) [0x7fff8b53d227] 1-21
                                              21  ___CFXRegistrationPost_block_invoke + 63 (CoreFoundation + 660143) [0x7fff8b53d2af] 1-21
                                                21  __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 12 (CoreFoundation + 660252) [0x7fff8b53d31c] 1-21
                                                  21  ??? (Pecunia + 82600) [0x105fcd2a8] 1-21
                                                    21  ??? (Pecunia + 102334) [0x105fd1fbe] 1-21
                                                      21  ??? (Pecunia + 126942) [0x105fd7fde] 1-21
                                                        21  objc_msgSend + 209 (libobjc.A.dylib + 5521) [0x7fff91708591] 1-21
                                                          21  lookUpImpOrForward + 179 (libobjc.A.dylib + 27912) [0x7fff9170dd08] 1-21
                                                            21  _class_initialize + 711 (libobjc.A.dylib + 29640) [0x7fff9170e3c8] 1-21
                                                              21  ??? (Pecunia + 1620351) [0x10614497f] 1-21
                                                                18  ??? (Pecunia + 1631649) [0x1061475a1] 1-18
                                                                  18  -[NSBundle classNamed:] + 85 (Foundation + 482713) [0x7fff88b50d99] 1-18
                                                                    18  +[NSBundle bundleForClass:] + 70 (Foundation + 87588) [0x7fff88af0624] 1-18
                                                                      18  class_respondsToSelector + 37 (libobjc.A.dylib + 44986) [0x7fff91711fba] 1-18
                                                                        18  lookUpImpOrNil + 20 (libobjc.A.dylib + 36239) [0x7fff9170fd8f] 1-18
                                                                          18  lookUpImpOrForward + 364 (libobjc.A.dylib + 28097) [0x7fff9170ddc1] 1-18
                                                                            18  _class_resolveMethod + 124 (libobjc.A.dylib + 42171) [0x7fff917114bb] 1-18
                                                                              18  objc_msgSend + 209 (libobjc.A.dylib + 5521) [0x7fff91708591] 1-18
                                                                                18  lookUpImpOrForward + 179 (libobjc.A.dylib + 27912) [0x7fff9170dd08] 1-18
                                                                                  18  _class_initialize + 711 (libobjc.A.dylib + 29640) [0x7fff9170e3c8] 1-18
                                                                                    18  ??? (Pecunia + 1482665) [0x106122fa9] 1-18
                                                                                      1   ??? (Pecunia + 1524672) [0x10612d3c0] 1
                                                                                        1   ??? (<5C6DC4CB-402D-3BDD-8CEE-DDCFA60B1D79> + 1568934) [0x10663c0a6] 1
                                                                                          1   ??? (<5C6DC4CB-402D-3BDD-8CEE-DDCFA60B1D79> + 1355832) [0x106608038] (running) 1
                                                                                      1   ??? (Pecunia + 1521968) [0x10612c930] 2
                                                                                        1   ??? (<5C6DC4CB-402D-3BDD-8CEE-DDCFA60B1D79> + 1569503) [0x10663c2df] 2
                                                                                          1   OSAtomicCompareAndSwapPtrBarrier$VARIANT$mp + 8 (libsystem_platform.dylib + 6628) [0x7fff876cd9e4] (running) 2
                                                                                      1   ??? (Pecunia + 1525940) [0x10612d8b4] 3
                                                                                        1   ??? (<5C6DC4CB-402D-3BDD-8CEE-DDCFA60B1D79> + 1568801) [0x10663c021] 3
                                                                                          1   CFRelease + 162 (CoreFoundation + 60338) [0x7fff8b4aabb2] (running) 3
                                                                                      2   ??? (Pecunia + 1527280) [0x10612ddf0] 4-5
                                                                                        1   objc_msgSend + 13 (libobjc.A.dylib + 5325) [0x7fff917084cd] (running) 4
                                                                                        1   ??? (<5C6DC4CB-402D-3BDD-8CEE-DDCFA60B1D79> + 1568719) [0x10663bfcf] 5
                                                                                          1   -[__NSCFString retain] + 14 (CoreFoundation + 360766) [0x7fff8b4f413e] 5
                                                                                            1   OSAtomicCompareAndSwapPtrBarrier$VARIANT$mp + 8 (libsystem_platform.dylib + 6628) [0x7fff876cd9e4] (running) 5
                                                                                      1   ??? (Pecunia + 1523540) [0x10612cf54] 6
                                                                                        1   ??? (<5C6DC4CB-402D-3BDD-8CEE-DDCFA60B1D79> + 1568913) [0x10663c091] 6
                                                                                          1   -[__NSCFString retain] + 14 (CoreFoundation + 360766) [0x7fff8b4f413e] 6
                                                                                            1   OSAtomicCompareAndSwapPtrBarrier$VARIANT$up + 16 (libsystem_platform.dylib + 6620) [0x7fff876cd9dc] (running) 6
                                                                                      1   ??? (Pecunia + 1524672) [0x10612d3c0] 7
                                                                                        1   objc_msgSend + 46 (libobjc.A.dylib + 5358) [0x7fff917084ee] (running) 7
                                                                                      1   ??? (Pecunia + 1522820) [0x10612cc84] 8
                                                                                        1   ??? (<5C6DC4CB-402D-3BDD-8CEE-DDCFA60B1D79> + 1568719) [0x10663bfcf] 8
                                                                                          1   -[__NSCFString retain] + 14 (CoreFoundation + 360766) [0x7fff8b4f413e] 8
                                                                                            1   OSAtomicCompareAndSwapPtrBarrier$VARIANT$mp + 8 (libsystem_platform.dylib + 6628) [0x7fff876cd9e4] (running) 8
                                                                                      1   ??? (Pecunia + 1524672) [0x10612d3c0] 9
                                                                                        1   ??? (<5C6DC4CB-402D-3BDD-8CEE-DDCFA60B1D79> + 1569444) [0x10663c2a4] 9
                                                                                          1   ??? (<5C6DC4CB-402D-3BDD-8CEE-DDCFA60B1D79> + 1356084) [0x106608134] (running) 9
                                                                                      1   ??? (Pecunia + 1525744) [0x10612d7f0] 10
                                                                                        1   ??? (<5C6DC4CB-402D-3BDD-8CEE-DDCFA60B1D79> + 1569609) [0x10663c349] 10
                                                                                          1   CFRelease + 80 (CoreFoundation + 60256) [0x7fff8b4aab60] (running) 10
                                                                                      1   ??? (Pecunia + 1527476) [0x10612deb4] 11
                                                                                        1   ??? (<5C6DC4CB-402D-3BDD-8CEE-DDCFA60B1D79> + 1568921) [0x10663c099] 11
                                                                                          1   -[__NSCFString retain] + 14 (CoreFoundation + 360766) [0x7fff8b4f413e] 11
                                                                                            1   CFRetain + 81 (CoreFoundation + 30545) [0x7fff8b4a3751] 11
                                                                                              1   object_getClass + 4 (libobjc.A.dylib + 37753) [0x7fff91710379] (running) 11
                                                                                      1   ??? (Pecunia + 1518287) [0x10612bacf] 12
                                                                                        1   ??? (<5C6DC4CB-402D-3BDD-8CEE-DDCFA60B1D79> + 1568913) [0x10663c091] 12
                                                                                          1   -[__NSCFString retain] + 14 (CoreFoundation + 360766) [0x7fff8b4f413e] 12
                                                                                            1   CFRetain + 35 (CoreFoundation + 30499) [0x7fff8b4a3723] (running) 12
                                                                                      2   ??? (Pecunia + 1524000) [0x10612d120] 13-14
                                                                                        1   ??? (<5C6DC4CB-402D-3BDD-8CEE-DDCFA60B1D79> + 1568801) [0x10663c021] 13
                                                                                          1   CFRelease + 12 (CoreFoundation + 60188) [0x7fff8b4aab1c] (running) 13
                                                                                        1   ??? (<5C6DC4CB-402D-3BDD-8CEE-DDCFA60B1D79> + 1568934) [0x10663c0a6] 14
                                                                                          1   ??? (<5C6DC4CB-402D-3BDD-8CEE-DDCFA60B1D79> + 1355998) [0x1066080de] 14
                                                                                            1   CFRelease + 779 (CoreFoundation + 60955) [0x7fff8b4aae1b] (running) 14
                                                                                      1   ??? (Pecunia + 1523540) [0x10612cf54] 15
                                                                                        1   ??? (<5C6DC4CB-402D-3BDD-8CEE-DDCFA60B1D79> + 1569625) [0x10663c359] 15
                                                                                          1   CFRelease + 282 (CoreFoundation + 60458) [0x7fff8b4aac2a] (running) 15
                                                                                      1   ??? (Pecunia + 1518521) [0x10612bbb9] 16
                                                                                        1   ??? (<5C6DC4CB-402D-3BDD-8CEE-DDCFA60B1D79> + 1568994) [0x10663c0e2] 16
                                                                                          1   CFRelease + 801 (CoreFoundation + 60977) [0x7fff8b4aae31] (running) 16
                                                                                      1   ??? (Pecunia + 1525940) [0x10612d8b4] 17
                                                                                        1   ??? (<5C6DC4CB-402D-3BDD-8CEE-DDCFA60B1D79> + 1568934) [0x10663c0a6] 17
                                                                                          1   ??? (<5C6DC4CB-402D-3BDD-8CEE-DDCFA60B1D79> + 1355944) [0x1066080a8] 17
                                                                                            1   ??? (<5C6DC4CB-402D-3BDD-8CEE-DDCFA60B1D79> + 2385396) [0x1067035f4] (running) 17
                                                                                      1   ??? (Pecunia + 1525736) [0x10612d7e8] 18
                                                                                        1   -[__NSCFString retain] + 14 (CoreFoundation + 360766) [0x7fff8b4f413e] 18
                                                                                          1   CFRetain + 81 (CoreFoundation + 30545) [0x7fff8b4a3751] 18
                                                                                            1   object_getClass + 4 (libobjc.A.dylib + 37753) [0x7fff91710379] (running) 18
                                                                1   ??? (Pecunia + 1631263) [0x10614741f] 19
                                                                  1   -[NSString componentsSeparatedByString:] + 67 (Foundation + 313134) [0x7fff88b2772e] 19
                                                                    1   -[NSString rangeOfString:options:range:] + 29 (Foundation + 40688) [0x7fff88ae4ef0] 19
                                                                      1   -[NSString rangeOfString:options:range:locale:] + 388 (Foundation + 20680) [0x7fff88ae00c8] (running) 19
                                                                1   ??? (Pecunia + 1631286) [0x106147436] 20
                                                                  1   ??? (<D90B41AE-715A-3D71-9F4A-EB0F6F7C9EFA> + 23337) [0x1069f6b29] 20
                                                                    1   ??? (<D90B41AE-715A-3D71-9F4A-EB0F6F7C9EFA> + 23682) [0x1069f6c82] 20
                                                                      1   ??? (<D90B41AE-715A-3D71-9F4A-EB0F6F7C9EFA> + 109367) [0x106a0bb37] 20
                                                                        1   ??? (<5C6DC4CB-402D-3BDD-8CEE-DDCFA60B1D79> + 130111) [0x1064dcc3f] 20
                                                                          1   ??? (<5C6DC4CB-402D-3BDD-8CEE-DDCFA60B1D79> + 2010352) [0x1066a7cf0] (running) 20
                                                                1   ??? (Pecunia + 1636211) [0x106148773] 21
                                                                  1   ??? (<5C6DC4CB-402D-3BDD-8CEE-DDCFA60B1D79> + 1568740) [0x10663bfe4] 21
                                                                    1   ??? (<5C6DC4CB-402D-3BDD-8CEE-DDCFA60B1D79> + 1356161) [0x106608181] 21
                                                                      1   ??? (<5C6DC4CB-402D-3BDD-8CEE-DDCFA60B1D79> + 1565291) [0x10663b26b] 21
                                                                        1   CFStringGetCharacterAtIndex + 116 (CoreFoundation + 71204) [0x7fff8b4ad624] (running) 21

      Thread 0x47e32          DispatchQueue 2         21 samples (1-21)       priority 46 (base 46)
      <thread QoS user interactive (requested user interactive), process unclamped, process received importance donation from WindowServer [183], IO policy important>
      21  _dispatch_mgr_thread + 52 (libdispatch.dylib + 32001) [0x7fff85e4fd01] 1-21
        21  kevent_qos + 10 (libsystem_kernel.dylib + 98074) [0x7fff92d85f1a] 1-21
         *21  ??? (kernel + 5829712) [0xffffff800078f450] 1-21

      Thread 0x47e8d          21 samples (1-21)       priority 31 (base 31)
      <thread QoS legacy (requested legacy), process unclamped, process received importance donation from WindowServer [183], IO policy important>
      21  thread_start + 13 (libsystem_pthread.dylib + 4945) [0x7fff92d8e351] 1-21
        21  _pthread_start + 168 (libsystem_pthread.dylib + 14618) [0x7fff92d9091a] 1-21
          21  _pthread_body + 131 (libsystem_pthread.dylib + 14749) [0x7fff92d9099d] 1-21
            21  __NSThread__start__ + 1351 (Foundation + 220516) [0x7fff88b10d64] 1-21
              21  ??? (Pecunia + 446354) [0x106025f92] 1-21
                21  -[NSRunLoop(NSRunLoop) run] + 74 (Foundation + 150712) [0x7fff88affcb8] 1-21
                  21  -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 270 (Foundation + 151001) [0x7fff88affdd9] 1-21
                    21  CFRunLoopRunSpecific + 296 (CoreFoundation + 562744) [0x7fff8b525638] 1-21
                      21  __CFRunLoopRun + 1356 (CoreFoundation + 564716) [0x7fff8b525dec] 1-21
                        21  __CFRunLoopServiceMachPort + 212 (CoreFoundation + 567588) [0x7fff8b526924] 1-21
                          21  mach_msg_trap + 10 (libsystem_kernel.dylib + 69518) [0x7fff92d7ef8e] 1-21
                           *21  ipc_mqueue_receive_continue + 0 (kernel + 816720) [0xffffff80002c7650] 1-21

      Thread 0x47ed7          21 samples (1-21)       priority 46 (base 46)
      <thread QoS user interactive (requested user interactive), process unclamped, process received importance donation from WindowServer [183], IO policy important>
      21  thread_start + 13 (libsystem_pthread.dylib + 4945) [0x7fff92d8e351] 1-21
        21  _pthread_start + 168 (libsystem_pthread.dylib + 14618) [0x7fff92d9091a] 1-21
          21  _pthread_body + 131 (libsystem_pthread.dylib + 14749) [0x7fff92d9099d] 1-21
            21  _NSEventThread + 149 (AppKit + 1702765) [0x7fff92f8bb6d] 1-21
              21  CFRunLoopRunSpecific + 296 (CoreFoundation + 562744) [0x7fff8b525638] 1-21
                21  __CFRunLoopRun + 1356 (CoreFoundation + 564716) [0x7fff8b525dec] 1-21
                  21  __CFRunLoopServiceMachPort + 212 (CoreFoundation + 567588) [0x7fff8b526924] 1-21
                    21  mach_msg_trap + 10 (libsystem_kernel.dylib + 69518) [0x7fff92d7ef8e] 1-21
                     *21  ipc_mqueue_receive_continue + 0 (kernel + 816720) [0xffffff80002c7650] 1-21

      Binary Images:
             0x105fb9000 -        0x106207fff  de.pecuniabanking.pecunia 1.2.1 (1.2.104) <DFA3090E-7DF2-3F52-9FDC-4882AA1CF527>  /Applications/Pecunia.app/Contents/MacOS/Pecunia
             0x1064bd000 -                ???  ???                                       <5C6DC4CB-402D-3BDD-8CEE-DDCFA60B1D79>
             0x1069f1000 -                ???  ???                                       <D90B41AE-715A-3D71-9F4A-EB0F6F7C9EFA>
          0x7fff80f0d000 -     0x7fff80f10fff  libdyld.dylib (360.20)                    <9B7D87EB-46E1-384A-8315-3295F71BA376>  /usr/lib/system/libdyld.dylib
          0x7fff8453b000 -     0x7fff84830fff  com.apple.HIToolbox 2.1.1 (807.2)         <871E5223-5D03-3649-98AF-9CCA3B41E307>  /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/HIToolbox.framework/Versions/A/HIToolbox
          0x7fff85e48000 -     0x7fff85e75fff  libdispatch.dylib (501.40.10)             <E55D2ED5-6839-3F7D-BDD6-2FB25C23F63D>  /usr/lib/system/libdispatch.dylib
          0x7fff876cc000 -     0x7fff876d4fff  libsystem_platform.dylib (74.40.2)        <29A905EF-6777-3C33-82B0-6C3A88C4BA15>  /usr/lib/system/libsystem_platform.dylib
          0x7fff88adb000 -     0x7fff88e2ffff  com.apple.Foundation 6.9 (1258)           <FDC34FEB-1206-31E5-8E6F-A3F7F3E8BD4D>  /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
          0x7fff8b49c000 -     0x7fff8b912fff  com.apple.CoreFoundation 6.9 (1258)       <21EBA6F2-D078-335D-9CAA-76EC08CB4CC3>  /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
          0x7fff8eeaa000 -     0x7fff8eefffff  com.apple.AE 701 (701)                    <AD492742-F884-386B-A450-FAC281B9FFA4>  /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/AE.framework/Versions/A/AE
          0x7fff91707000 -     0x7fff91a69fff  libobjc.A.dylib (680)                     <7489D2D6-1EFD-3414-B18D-2AECCCC90286>  /usr/lib/libobjc.A.dylib
          0x7fff92d6e000 -     0x7fff92d8cfff  libsystem_kernel.dylib (3248.40.155)      <AC3916B4-4B39-39DE-8AC8-2E0D1674F944>  /usr/lib/system/libsystem_kernel.dylib
          0x7fff92d8d000 -     0x7fff92d96fff  libsystem_pthread.dylib (138.10.4)        <3DD1EF4C-1D1B-3ABF-8CC6-B3B1CEEE9559>  /usr/lib/system/libsystem_pthread.dylib
          0x7fff92dec000 -     0x7fff93a15fff  com.apple.AppKit 6.9 (1404.41)            <472D842D-B906-31CF-A785-070663856E18>  /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
     *0xffffff8000200000 - 0xffffff80009fffff  kernel (3248.40.155)                      <B7E5FF7D-220B-3B97-A3B9-9952EBDE6F6D>  /System/Library/Kernels/kernel

**Comment by mike-lischke** [comment]
Und das gleiche passiert jedes Mal, wenn Pecunia gestartet wird?

**Comment by Debilski** [comment]
Ja, musste wieder die 1.1.6 von der Homepage installieren, um es nutzen zu können. Hoffe, der Vereinswechsel führt jetzt nicht zu anderen Problemen.

Hab auch die 1.2.1 mit neuem Container-Profil erstellt und nur die alte accounts.pecuniadata rüberkopiert und so läuft es auch noch in 1.1.6, aber eben nicht mit der neuesten Version.

**Comment by mike-lischke** [comment]
Und die 1.2 von der Homepage hat ebenfalls das gleiche Problem? Wir haben die schon eine ganze Weile online, ohne von so einem crash gehört zu haben.

**Comment by Debilski** [comment]
Die 1.2 hatte das Problem schon immer (oder zumindest ein ähnliches). Habe die früher schon getestet, aber nicht weiter debuggt, weil ich dachte, dass das mit ein Grund wäre, aus dem sie aus dem App Store zurückgezogen wurde.

Exportieren kann ich mal versuchen, allerdings wollte ich jetzt nicht alle meine Konten neu anlegen und mir ist auch nicht klar, welche Felder ich da für den Export auswählen muss.

**Comment by Debilski** [comment]
Wenn ich den alten Container verschiebe und 1.2.1 zum ersten Mal starte bekomme ich die folgende Ausgabe:

    $ /Applications/Pecunia.app/Contents/MacOS/Pecunia
    2016-01-23 11:35:28.333 Pecunia[6946:476898] DDFileLogManagerDefault: Error creating logsDirectory: Error Domain=NSCocoaErrorDomain Code=516 "Die Datei „Pecunia“ konnte nicht im Ordner „Logs“ gesichert werden, da bereits eine Datei mit diesem Namen existiert." UserInfo={NSFilePath=$HOME/Library/Containers/de.pecuniabanking.pecunia/Data/Library/Logs/Pecunia, NSUnderlyingError=0x7fb4d3e393a0 {Error Domain=NSPOSIXErrorDomain Code=17 "File exists"}}
    HBCI Server up and running...
    2016-01-23 11:35:28.603 Pecunia[6946:476898] CoreData: Failed to load optimized model at path '/Applications/Pecunia.app/Contents/Resources/Accounts.momd/Accounts 15.omo'
    2016-01-23 11:35:45.376 Pecunia[6946:476898] +entityForName: nil is not a legal NSManagedObjectContext parameter searching for entity name 'Transfer'

Und Pecunia zeigt ein Popup an:

    Die Datei „accounts.sqlite“ konnte nicht geöffnet werden, da sie nicht existiert.

Nach Ok-Drücken beendet sich Pecunia. Starte ich danach erneut sieht alles gut aus, trotz der Kommandozeilenausgabe

    $ /Applications/Pecunia.app/Contents/MacOS/Pecunia
    HBCI Server up and running...
    2016-01-23 11:35:49.133 Pecunia[6971:478708] CoreData: Failed to load optimized model at path '/Applications/Pecunia.app/Contents/Resources/Accounts.momd/Accounts 15.omo'

kommt dann „Bankkennung anlegen“ und alles scheint normal zu sein.

**Comment by gituser99** [comment]
Bei mir kommt mit dem Upgrade auf 1.2.1 aus dem MacStore das gleiche Verhalten. Pecunia startet mit dem Popup zum Verwendungszweck SEPA.
Wenn ich aus dem Terminal starte kommt eine ähnliche Meldung wie hier im ersten post beschrieben. Lediglich die Werte in den [] sind unterschiedlich. Da ich mitlerweile wieder die alte Versio von der Website installiert habe, weiß ich die Nummern aber nicht mehr.

Ein Downgrade auf 1.6.1 war ohne Probleme möglich. Ich musste nicht den alten Container wiederherstellen.
Mac ElCapitain mit neuesten Updates auf MacBook Air.

**Comment by Debilski** [comment]
Debugge es gerade. Problem bei mir scheint zu sein, dass `computeChecksum(iban: NSString) -> Int` eine IBAN mit Leerzeichen bekommt. Sie sieht etwa so aus: `AT 803dddddddd…`. Der Part ` 8` wird dann nach weiteren Umformungen an die Funktion `mod97` gepackt, die dann für das Leerzeichen natürlich im Part `Int(String(c))!` aufgibt. (`mod97` sollte also wohl besser selber ein `Int?` zurück geben, aber der Fehler passiert wohl früher.)

Folgende Änderungen in `Submodules/IBANtools/Source/Converter.swift`

    -    return computeChecksum(iban!) == 97;
    +    let trimmed = iban?.stringByReplacingOccurrencesOfString(" ", withString: "");
    +    return computeChecksum(trimmed!) == 97;

beheben das Problem (d.h. ich kann die allerneueste Version starten!), aber da mein Wissen über IBANs auch nur begrenzt ist, ist es vielleicht schlauer, solche Normalisierungen der Datenbank an andere Stelle einzubauen.

**Comment by mike-lischke** [comment]
Wunderbar. darauf wäre ich nicht gekommen. Die Fehlermeldungen in der Konsole sind ja mal wieder völlig für die Tonne. Dein Fix ist völlig in Ordnung. Die Leerzeichen sind nur Formatierungshilfen und der IBAN Code sollte natürlich damit umgehen können. Das hatte ich nicht bedacht.

Darf ich fragen, welche Bank das ist? Ich habe bisher kaum von einer österreichischen Bank gehört, die HBCI unterstützt.

**Comment by Debilski** [comment]
Mit der gepatchten Version sind dann auch noch falsch normalisierte Einträge in der accounts.sqlite, wenn ich ein `select zremoteiban from zbankstatement` durchführe (allerdings wohl nur für nicht-DE-Banken). Da diese Spalte vor dem Update leer ist, nehme ich an, dass dort beim Generieren etwas schief geht.

**Comment by Debilski** [comment]
Ist ja nicht meine eigene Bank, sondern wohl von Leuten, denen ich mal etwas überwiesen habe.

**Comment by mike-lischke** [comment]
Fixed in [868f438acb482cf1a1bea0277faf8cfb2152ad06](https://github.com/mike-lischke/IBANTools/commit/868f438acb482cf1a1bea0277faf8cfb2152ad06).

**Comment by mike-lischke** [comment]
Die Einträge in der DB sollten kein Problem darstellen. Vielleicht normalisieren wir die ebenfalls mal noch, aber wichtiger ist der lib code, der damit arbeiten muss.

Danke für deine Hilfe.

**Comment by Debilski** [comment]
Kein Problem. Xcode hat mir glücklicherweise recht schnell gezeigt, wo das Problem lag.
