### ISSUE TITLE
Absturz bei Start

### ISSUE THREAD

**Issue by olgierdgogolin** [pecuniabanking/pecunia-client#435]
Ich habe das Update auf 1.2.1 über den App-Store durchgeführt. Es sollte eine Aktualisierung der Datenbank durchgeführt werden. Seitdem stürzt die App bei Start ab. Ich arbeite mit El Capitan.

**Comment by mike-lischke** [comment]
Ja, leider hat sich da ein Fehler eingeschlichen. Das ist vermutlich der gleiche Fehler, wie in #434.

**Comment by mike-lischke** [comment]
Hey Frank,

> Ich habe das Update auf 121 über den App-Store durchgeführt Es sollte eine Aktualisierung der Datenbank durchgeführt werden Seitdem stürzt die App bei Start ab Ich arbeite mit El Capitan

Ich fürchte, wir müssen bald ein bug fix release nachschieben. Da hat sich ein blöder Fehler in den IBANtools eingeschlichen. Gefixt ist er aber schon.

Mike
-- 
www.soft-gems.net

**Comment by olgierdgogolin** [comment]
Vielen Dank!
Olgierd
