### ISSUE TITLE
Nach Update auf 1.2.1 sehr große Datendatei

### ISSUE THREAD

**Issue by danielmjacob** [pecuniabanking/pecunia-client#441]
Ich bin mir nicht sicher, ob's ein Bug ist, aber bemerkenswert ist es doch. Beim Aktualisieren der Datendatei nach dem Update auf 1.2.1 ist die Datendatei von zuvor etwa etwa 1,6 MB auf 116 MB angewachsen.

**Comment by mike-lischke** [comment]
Daniel, bist du sicher es ist die Datendatei (accounts.pecuniadata)? Es gibt jetzt eine neue shared DB, die für Daten benutzt wird, die man nachladen kann und die auch von mehreren Pecuniainstallationen verwendet werden kann.

**Comment by danielmjacob** [comment]
Hallo Mike, 

entschuldige bitte, dass ich mich jetzt erst melde. Ja, ich meine die Datendatei. Ich habe mal reingeguckt und genauer scheint es die Datei "accounts.sqlite" zu sein, die sich seit dem Update so aufgebläht hat. Neben meinen Kontodaten sieht es so aus, als wäre da ein umfangreiches, aber etwas eigenartiges Wörterbuch drin, soll das so sein?

> ‚&ÅÍ<++Arbeitshandbucharbeitshandbuch6ÅÍ;;;Aufkl√§rungsergebnissesaufklaerungsergebnisses$ÅÍ:))√§stimierendemaestimierendem0ÅÍ955Arbeiterwochenkartenarbeiterwochenkarten$ÅÍ8))Apfelweinseiteapfelweinseite*ÅÍ7//Annoncenbl√§tternannoncenblaettern2ÅÍ677Artillerieschulschiffartillerieschulschiff ÅÍ5%%aufgeheitertaufgeheitert"ÅÍ4''anr√ºchigsteranruechigster"ÅÍ3''Aufgabestelleaufgabestelle(ÅÍ2--anstandswidrigemanstandswidrigem(ÅÍ1--Anfahrkupplungenanfahrkupplungen.ÅÍ033aufeinanderzupassenaufeinanderzupassen8ÅÍ/==√Ñnderungs√ºberwachungenaenderungsueberwachungen&ÅÍ.++Anschlagsoptionanschlagsoption"ÅÍ-''Anrufvolumensanrufvolumens(ÅÍ,--ArbeitslohnkartearbeitslohnkarteÅÍ+anbellstanbellst2ÅÍ*77AntennendosentauschesantennendosentauschesÅÍ)!!ank√§mpfteankaempfte ÅÍ(%%aufgewarteteaufgewartete$ÅÍ'))Anlagenklassenanlagenklassen*ÅÍ&//ArchitektenbundesarchitektenbundesÅÍ%Artikelsartikels*ÅÍ$//Artikelverteilungartikelverteilung"ÅÍ#''AtomstationenatomstationenÅÍ"!!ansuchtestansuchtest&ÅÍ!++Aristotelikerinaristotelikerin&ÅÍ ++Anlagenmodellenanlagenmodellen.ÅÍ33Arbeitsmodellierungarbeitsmodellierung"ÅÍ''AnteilsystemsanteilsystemsÅÍ##Anbauphasenanbauphasen2ÅÍ77√Ñnderungsinformationaenderungsinformation

**Comment by mike-lischke** [comment]
Hmm, ja, das ist das Wörterbuch, was Pecunia für das true-casing (also die richtige Groß-/Kleinschreibung) verwendet. Das sollte allerdings nicht in accounts.sqlite landen sondern in shared.sqlite. Sehr sonderbar.

**Comment by danielmjacob** [comment]
Hallo Mike, das Problem besteht immer noch. Gibt es vielleicht eine Möglichkeit, die Daten inklusive der Kategorien zu exportieren und in eine neue Datendatei zu importieren? Danke & mit besten Grüßen, Daniel

**Comment by danielmjacob** [comment]
Ich habe jetzt eine Art workaround gefunden: ich habe eine neue Datendatei erstellt, aus der alten Datendatei alle Tabellen bis auf "ZWordmapping" exportiert und die exportierten Tabellen dann in die neue Datei importiert. Funktioniert!

**Comment by mike-lischke** [comment]
Ok, das geht natürlich auch, obwohl ich nicht verstehe, warum das Wörterbuch überhaupt in deiner Hauptdatendatei aufgetaucht ist. Bisher habe ich auch noch keinen anderen solchen Fall gehört. Nun gut, für diesmal gelöst :-)
