### ISSUE TITLE
Markierung in Konten- und Kategorien nicht Sichtbar

### ISSUE THREAD

**Issue by schneiderst** [pecuniabanking/pecunia-client#443]
Hallo, 

in meinem aktuellen Compilat wird in der Konten- und Kategorienavigation die aktuelle Auswahl nicht mehr angezeigt sobald ich in einem anderen Fensterbereich navigiere. Damit ist z.B. in der Verlaufsanzeige nach Auswahl einer anderen Skalierung nicht mehr nachvollziehbar welche Kategorien oder Konten angezeigt werden.

Gruß,
Stefan

**Comment by mike-lischke** [comment]
Fixed in 9638d290f021a5865f4122a5f8083ecfedd9e04a

**Comment by mike-lischke** [comment]
Tatsächlich ist Implementation über mehrere commits verteilt. Ich verlinke hier nur einen davon.
