### ISSUE TITLE
Absturz beim Öffnen von Überweisung

### ISSUE THREAD

**Issue by easysailer** [pecuniabanking/pecunia-client#444]
Beim Klick auf den Button "Überweisungen" erscheint kurz die leere Überweisungsliste, dann wird das Programm komplett geschlossen.

OSX10.10.5 und Pecunia 1.21
Ich hatte hier schon ein Problem bei V1.21. gemeldet, weil ich Pecunia garnicht starten konnte. Ich bin dann zurück auf die alte Version um erstmal wieder arbeiten zu können, leider hat sich das Update wieder selber installiert. Nun startet zwar die Software, aber wie oben beschrieben stürzt sie ab.

**Comment by mike-lischke** [comment]
Mittlerweile ist die 1.2.2 im AppStore. Hat sich damit die Situation verbessert?

**Comment by easysailer** [comment]
Hallo,
vielen Dank erstmal für die Mühe.

Hab grad installiert, leider hat es sich nicht verbessert.
Das Programm startet ganz normal. Umsätze lassen sich aktualisieren und auch die Daueraufträge lassen sich aufrufen.
Nur beim Versuch die Überweisungen aufzurufen kommt es zum Absturz. Die leere Maske wird noch geladen, dann scheint es so, als würde versucht werden die Liste der bisher getätigten Überweisungen zu laden. Der Cursor hat auch die Form eines Kreises in Regenbogenfarben. Dieser Vorgang dauert ca. 1sek dann schließt sich Pecunia ohne weitere Meldungen.


VG
Mike Focke

**Comment by mike-lischke** [comment]
Zu diesem Zeitpunkt wird gewöhnlich die IBANtools lib geladen. Vielleicht schlägt dabei etwas fehlt. Das müssen wir uns später noch im Detail ansehen. Leider kann ich im Moment keinen workaround anbieten.

**Comment by macemmi** [comment]
Fixed

**Comment by easysailer** [comment]
Das Problem ist immer noch nicht behoben. Mittlerweile verwende ich  OS 10.11.5 und hab gerade die Pecunia Version 1.3.005 installiert. Die Software startet ganz normal aber sobald man auf den Tab Überweisungen klickt, schließt sich das Programm komplett.

**Comment by macemmi** [comment]
Hallo,

das wird ein Problem mit der IBAN-Konvertierung sein. Bitte mal nach dem Absturz die Logdatei (Hilfe->Log) schicken.

Mit freundlichen Grüßen
Frank Emminghaus

Pecunia Development & Support
http://www.pecuniabanking.de

**Comment by easysailer** [comment]
Hallo,
ich hab Pecunia heute genau 2x geöffnet. Das erste Mal um den Absturz zu erzeugen und das zweite Mal um die Logs zu kopieren.
In der Anlage befinden sich die beiden Log Dateien davon.
Vielen Dank schonmal für die Mühe. 

Viele Grüße
Mike

**Comment by macemmi** [comment]
Hallo,

ich sehe keine Logs. Logs bitte nur an die Supportadresse schicken (support@pecuniabanking.de <mailto:support@pecuniabanking.de>), am besten verschlüsselt.

Mit freundlichen Grüßen
Frank Emminghaus

Pecunia Development & Support
http://www.pecuniabanking.de
