### ISSUE TITLE
Pecunia is asking for a password (since 1.2.1)

### ISSUE THREAD

**Issue by seniorgod** [pecuniabanking/pecunia-client#447]
Since 1.2.1  Pecunia  is asking for a password to open the database.
Because Pecunia never do this since i use it (for several years), i don't know it.
Why is Pecunia asking it right now and never before?
What can i do now?

**Comment by mike-lischke** [comment]
This is fixed in 1.2.2 available now from the AppStore.

**Comment by seniorgod** [comment]
Kann ich leider nicht bestätigen

**Comment by mike-lischke** [comment]
Ok, dann habe ich mich wohl vertan. In der nächsten Version sollte es dann aber gefixt sein.

**Comment by seniorgod** [comment]
Hallo,

ich habe jetzt 1.2.3 geladen. 
Das gleiche Verhalten wie seit 1.2.1. 
Pecunia startet, zeigt eine Passwortabfrage mit vorausgefülltem Passwort. Ein Druck auf den Button "Entschlüsseln" führt nicht zum Erfolg.Ich habe/hatte seit 2013 nie wieder dieses Passwort eingeben müssen und kenne es daher nicht mehr. Die Einträge im Schlüsselbund, die ich unter dem Suchwort pecunia finde sind von 2013 und 2014. Warum fragt Pecunia mich plötzlich danach. Muss ich meine Daten jetzt als verloren betrachten?

**Comment by macemmi** [comment]
Hallo,

ein Bug in der Version 1.2.0 hat dazu geführt dass das Passwort im Schlüsselbund gelöscht wird. 
Um das Passwort zu erfahren muss man ein TimeMachine-Backup des Schlüsselbundes zurückholen.
Dazu im Ordner ~/Library/Keychains TimeMachine starten und die Datei login.keychain zurückholen. Wichtig ist dass man "beide behalten" auswählen sollte, damit nicht der aktuelle Schlüsselbund überschrieben wird. Dann den Schlüsselbund öffnen und nach "DataFile" suchen. Hinter dem Eintrag steht dann das Passwort.

**Comment by seniorgod** [comment]
Hat funktioniert. Danke!
