### ISSUE TITLE
Pecunia startet nicht nach Update auf 1.2.2

### ISSUE THREAD

**Issue by izzycole** [pecuniabanking/pecunia-client#449]
Bin erstmal wieder auf 1.2.1. 

Letzte Log-Datei:

2016/02/11 15:51:24:406  [Info] Starting up application
2016/02/11 15:51:24:406  [Info] Arguments: (
    "/Applications/Pecunia.app/Contents/MacOS/Pecunia"
)
2016/02/11 15:51:24:406  [Info] Pecunia version: 1.2.2
2016/02/11 15:51:24:407  [Info] Machine + OS: Macmini6,2, Version 10.9.5 (Build 13F1134)
2016/02/11 15:51:24:407  [Info] Mem size: 16.0GB
2016/02/11 15:51:24:407  [Info] CPU : Intel(R) Core(TM) i7-3720QM CPU @ 2.60GHz
2016/02/11 15:51:24:407  [Info] Process environment: {
    "APP_SANDBOX_CONTAINER_ID" = "de.pecuniabanking.pecunia";
    "Apple_PubSub_Socket_Render" = "/tmp/launch-IZPNDy/Render";
    "CFFIXED_USER_HOME" = "/Users/izzycole/Library/Containers/de.pecuniabanking.pecunia/Data";
    DISPLAY = "/tmp/launch-X43UgK/org.macosforge.xquartz:0";
    HOME = "/Users/izzycole/Library/Containers/de.pecuniabanking.pecunia/Data";
    LOGNAME = izzycole;
    PATH = "/usr/bin:/bin:/usr/sbin:/sbin";
    SHELL = "/bin/bash";
    "SSH_AUTH_SOCK" = "/tmp/launch-sBnOMG/Listeners";
    TMPDIR = "/var/folders/y1/4mxrys5j2l30z3ybm20dvdpr0000gn/T/de.pecuniabanking.pecunia/";
    USER = izzycole;
    "__CF_USER_TEXT_ENCODING" = "0x1F5:0:3";
    "__CHECKFIX1436934" = 1;
}
2016/02/11 15:51:24:426  [Error] Exception reported by the runtime: [<NSButton 0x610000150d80> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key highlighted.
2016/02/11 15:51:24:426  [Error] 0   CoreFoundation                      0x00007fff8b2d725c __exceptionPreprocess + 172
2016/02/11 15:51:24:426  [Error] 1   libobjc.A.dylib                     0x00007fff8f053e75 objc_exception_throw + 43
2016/02/11 15:51:24:426  [Error] 2   CoreFoundation                      0x00007fff8b2d6e09 -[NSException raise] + 9
2016/02/11 15:51:24:426  [Error] 3   Foundation                          0x00007fff8c56cd4e -[NSObject(NSKeyValueCoding) setValue:forKey:] + 389
2016/02/11 15:51:24:426  [Error] 4   Foundation                          0x00007fff8c5a07f4 -[NSObject(NSKeyValueCoding) setValue:forKeyPath:] + 343
2016/02/11 15:51:24:426  [Error] 5   AppKit                              0x00007fff8a5e45a1 -[NSView setValue:forKeyPath:] + 392
2016/02/11 15:51:24:426  [Error] 6   AppKit                              0x00007fff8a6d9d60 -[NSIBUserDefinedRuntimeAttributesConnector establishConnection] + 325
2016/02/11 15:51:24:426  [Error] 7   AppKit                              0x00007fff8a3eea64 -[NSIBObjectData nibInstantiateWithOwner:topLevelObjects:] + 1004
2016/02/11 15:51:24:426  [Error] 8   AppKit                              0x00007fff8a492e5c -[NSNib _instantiateNibWithExternalNameTable:] + 600
2016/02/11 15:51:24:426  [Error] 9   AppKit                              0x00007fff8a5c2482 -[NSNib instantiateNibWithOwner:topLevelObjects:] + 215
2016/02/11 15:51:24:426  [Error] 10  AppKit                              0x00007fff8a5c2262 -[NSViewController loadView] + 180
2016/02/11 15:51:24:426  [Error] 11  Pecunia                             0x0000000106ff3e7b Pecunia + 396923
2016/02/11 15:51:24:426  [Error] 12  Pecunia                             0x0000000106fd1cf4 Pecunia + 257268
2016/02/11 15:51:24:426  [Error] 13  Pecunia                             0x0000000106fd83ac Pecunia + 283564
2016/02/11 15:51:24:426  [Error] 14  Pecunia                             0x0000000107045286 Pecunia + 729734
2016/02/11 15:51:24:426  [Error] 15  Pecunia                             0x0000000106f9508c Pecunia + 8332
2016/02/11 15:51:24:426  [Error] 16  AppKit                              0x00007fff8a3ef6f4 -[NSCustomObject nibInstantiate] + 368
2016/02/11 15:51:24:426  [Error] 17  AppKit                              0x00007fff8a3ef520 -[NSIBObjectData instantiateObject:] + 309
2016/02/11 15:51:24:426  [Error] 18  AppKit                              0x00007fff8a3ee815 -[NSIBObjectData nibInstantiateWithOwner:topLevelObjects:] + 413
2016/02/11 15:51:24:426  [Error] 19  AppKit                              0x00007fff8a3e35ce loadNib + 327
2016/02/11 15:51:24:426  [Error] 20  AppKit                              0x00007fff8a3e2b6c +[NSBundle(NSNibLoading) _loadNibFile:nameTable:withZone:ownerBundle:] + 288
2016/02/11 15:51:24:427  [Error] 21  AppKit                              0x00007fff8a3e295c -[NSBundle(NSNibLoading) loadNibNamed:owner:topLevelObjects:] + 197
2016/02/11 15:51:24:427  [Error] 22  AppKit                              0x00007fff8a3e274b +[NSBundle(NSNibLoading) loadNibNamed:owner:] + 357
2016/02/11 15:51:24:427  [Error] 23  AppKit                              0x00007fff8a3de597 NSApplicationMain + 448
2016/02/11 15:51:24:427  [Error] 24  libdyld.dylib                       0x00007fff8f6835fd start + 1
2016/02/11 15:51:24:427  [Error] 25  ???                                 0x0000000000000001 0x0 + 1
2016/02/11 15:51:24:427  [Error] An unhandled exception occurred: [<NSButton 0x610000150d80> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key highlighted.
2016/02/11 15:51:24:427  [Info] Target object info:
<NSButton: 0x610000150d80>
2016/02/11 15:51:24:428  [Error] 0   Pecunia                             0x0000000106fcb734 Pecunia + 231220
2016/02/11 15:51:24:428  [Error] 1   Pecunia                             0x0000000106fcb3c6 Pecunia + 230342
2016/02/11 15:51:24:428  [Error] 2   ExceptionHandling                   0x00007fff855fbe90 -[NSExceptionHandler _handleException:mask:] + 168
2016/02/11 15:51:24:428  [Error] 3   ExceptionHandling                   0x00007fff855fbc31 NSExceptionHandlerUncaughtExceptionHandler + 268
2016/02/11 15:51:24:429  [Error] 4   CoreFoundation                      0x00007fff8b2d7702 __handleUncaughtException + 706
2016/02/11 15:51:24:429  [Error] 5   libobjc.A.dylib                     0x00007fff8f054304 _ZL15_objc_terminatev + 94
2016/02/11 15:51:24:429  [Error] 6   libc++abi.dylib                     0x00007fff826f91d1 _ZSt11__terminatePFvvE + 8
2016/02/11 15:51:24:429  [Error] 7   libc++abi.dylib                     0x00007fff826f8c5b _ZN10__cxxabiv1L22exception_cleanup_funcE19_Unwind_Reason_CodeP17_Unwind_Exception + 0
2016/02/11 15:51:24:429  [Error] 8   libobjc.A.dylib                     0x00007fff8f053fa1 _ZL26_objc_exception_destructorPv + 0
2016/02/11 15:51:24:429  [Error] 9   CoreFoundation                      0x00007fff8b2d6e09 -[NSException raise] + 9
2016/02/11 15:51:24:429  [Error] 10  Foundation                          0x00007fff8c56cd4e -[NSObject(NSKeyValueCoding) setValue:forKey:] + 389
2016/02/11 15:51:24:429  [Error] 11  Foundation                          0x00007fff8c5a07f4 -[NSObject(NSKeyValueCoding) setValue:forKeyPath:] + 343
2016/02/11 15:51:24:429  [Error] 12  AppKit                              0x00007fff8a5e45a1 -[NSView setValue:forKeyPath:] + 392
2016/02/11 15:51:24:429  [Error] 13  AppKit                              0x00007fff8a6d9d60 -[NSIBUserDefinedRuntimeAttributesConnector establishConnection] + 325
2016/02/11 15:51:24:429  [Error] 14  AppKit                              0x00007fff8a3eea64 -[NSIBObjectData nibInstantiateWithOwner:topLevelObjects:] + 1004
2016/02/11 15:51:24:429  [Error] 15  AppKit                              0x00007fff8a492e5c -[NSNib _instantiateNibWithExternalNameTable:] + 600
2016/02/11 15:51:24:429  [Error] 16  AppKit                              0x00007fff8a5c2482 -[NSNib instantiateNibWithOwner:topLevelObjects:] + 215
2016/02/11 15:51:24:429  [Error] 17  AppKit                              0x00007fff8a5c2262 -[NSViewController loadView] + 180
2016/02/11 15:51:24:429  [Error] 18  Pecunia                             0x0000000106ff3e7b Pecunia + 396923
2016/02/11 15:51:24:429  [Error] 19  Pecunia                             0x0000000106fd1cf4 Pecunia + 257268
2016/02/11 15:51:24:429  [Error] 20  Pecunia                             0x0000000106fd83ac Pecunia + 283564
2016/02/11 15:51:24:429  [Error] 21  Pecunia                             0x0000000107045286 Pecunia + 729734
2016/02/11 15:51:24:429  [Error] 22  Pecunia                             0x0000000106f9508c Pecunia + 8332
2016/02/11 15:51:24:429  [Error] 23  AppKit                              0x00007fff8a3ef6f4 -[NSCustomObject nibInstantiate] + 368
2016/02/11 15:51:24:429  [Error] 24  AppKit                              0x00007fff8a3ef520 -[NSIBObjectData instantiateObject:] + 309
2016/02/11 15:51:24:429  [Error] 25  AppKit                              0x00007fff8a3ee815 -[NSIBObjectData nibInstantiateWithOwner:topLevelObjects:] + 413
2016/02/11 15:51:24:430  [Error] 26  AppKit                              0x00007fff8a3e35ce loadNib + 327
2016/02/11 15:51:24:430  [Error] 27  AppKit                              0x00007fff8a3e2b6c +[NSBundle(NSNibLoading) _loadNibFile:nameTable:withZone:ownerBundle:] + 288
2016/02/11 15:51:24:430  [Error] 28  AppKit                              0x00007fff8a3e295c -[NSBundle(NSNibLoading) loadNibNamed:owner:topLevelObjects:] + 197
2016/02/11 15:51:24:430  [Error] 29  AppKit                              0x00007fff8a3e274b +[NSBundle(NSNibLoading) loadNibNamed:owner:] + 357
2016/02/11 15:51:24:430  [Error] 30  AppKit                              0x00007fff8a3de597 NSApplicationMain + 448
2016/02/11 15:51:24:430  [Error] 31  libdyld.dylib                       0x00007fff8f6835fd start + 1
2016/02/11 15:51:24:430  [Error] 32  ???                                 0x0000000000000001 0x0 + 1

**Comment by mike-lischke** [comment]
Ja, das ist ein bekanntes Problem. Es wurde etwas verwendet, was es auf 10.9 nicht gibt. Leider gibt XCode da keinerlei Hilfe an (custom runtime attribute). Wir werden so schnell wie möglich eine weiteres bug fix release nachschieben.

**Comment by macemmi** [comment]
fixed mit 1.2.2
