### ISSUE TITLE
Kann Salo für manuell geführtes Konto nicht korrigieren

### ISSUE THREAD

**Issue by osopolar** [pecuniabanking/pecunia-client#450]
Ich führe ein Konto manuell, da es keine Schnittstelle gibt. Nun habe ich festgestellt, dass der Saldo nicht passt und habe versucht ihn manuell zu korrigieren:
* zuerst habe ich den Wert gelöscht und dachte er wird manuell neu berechnet,
* dann habe ich den aktuellen Saldo neu eingetragen aber er wird nicht gespeichert, denn wenn ich das Formular unter Konto > Eigenschaften erneut aufrufe, dann ist der Saldo leer, vgl. Screenshot

![konto_andern](https://cloud.githubusercontent.com/assets/1523215/13029701/1382ed5a-d272-11e5-9ff2-8fa43488194d.jpg)

Meine Pecunia Version ist 1.2.2 (1.2.200) aus dem App-Store, Mac OS Version ist 10.11.3 (15D21).

**Comment by macemmi** [comment]
Fixed
