### ISSUE TITLE
Pecunia druckt nicht und/oder stürzt ab

### ISSUE THREAD

**Issue by janstieler** [pecuniabanking/pecunia-client#454]
Hallo,

wenn ich eine Buchung drucken möchte, sieht man kurz dass das Menü Ablage aufblitzt und dann passiert gar nichts mehr.
Wenn ich per Maus auf das Drucken Menü gehe stürzt Pecunia ab.

Verwende Pecunia 1.2.3 (1.2.301).

Viele Grüße

**Comment by mike-lischke** [comment]
Ich kann dieses Problem nicht reproduzieren. Hängst du bitte mal dein Log hier an (siehe Hilfemenü), wenn der crash passiert. Achtung: bei jedem Start legt Pecunia ein neues Log an und rotiert die älteren 6.

**Comment by janstieler** [comment]
Hi,
ich hab mir mal das Log-Verzeichnis geöffnet und erstmal alle Logs gelöscht.
Dann habe ich eine Buchung die ich drucken wollte ausgewählt udn cmd+p gedrückt und nichts pasiert. Nach dem Shortcut hat Pecunia direkt einen Log angelegt.
Als ich dannach das Druckenmenü ausprobiert hatte stützte Pecunia wieder ab aber es wurde kein neuer Log nach dem Crash angelegt.
Anbei die Log-Datei welche nach dem Drucken Shortcut angelegt wurde:
`2016/03/08 15:02:33:432  [Error] Exception reported by the runtime: -[__NSCFString replaceCharactersInRange:withString:]: nil argument
2016/03/08 15:02:33:434  [Error] 0   CoreFoundation                      0x00007fff85317ae2 __exceptionPreprocess + 178
2016/03/08 15:02:33:434  [Error] 1   libobjc.A.dylib                     0x00007fff82712f7e objc_exception_throw + 48
2016/03/08 15:02:33:434  [Error] 2   CoreFoundation                      0x00007fff8531798d +[NSException raise:format:] + 205
2016/03/08 15:02:33:434  [Error] 3   CoreFoundation                      0x00007fff852d237f mutateError + 159
2016/03/08 15:02:33:434  [Error] 4   Foundation                          0x00007fff88431002 -[NSConcreteMutableAttributedString replaceCharactersInRange:withAttributedString:] + 286
2016/03/08 15:02:33:434  [Error] 5   Pecunia                             0x0000000105fd8bf5 Pecunia + 605173
2016/03/08 15:02:33:434  [Error] 6   Pecunia                             0x0000000105fd8351 Pecunia + 602961
2016/03/08 15:02:33:434  [Error] 7   Pecunia                             0x0000000105fda0f6 Pecunia + 610550
2016/03/08 15:02:33:434  [Error] 8   Pecunia                             0x0000000105fd7936 Pecunia + 600374
2016/03/08 15:02:33:434  [Error] 9   Pecunia                             0x000000010601c142 Pecunia + 880962
2016/03/08 15:02:33:434  [Error] 10  Pecunia                             0x0000000105f4dc8c Pecunia + 35980
2016/03/08 15:02:33:434  [Error] 11  libsystem_trace.dylib               0x00007fff951c807a _os_activity_initiate + 75
2016/03/08 15:02:33:435  [Error] 12  AppKit                              0x00007fff81c4651d -[NSApplication sendAction:to:from:] + 460
2016/03/08 15:02:33:435  [Error] 13  AppKit                              0x00007fff81c462b7 -[NSMenuItem _corePerformAction] + 336
2016/03/08 15:02:33:435  [Error] 14  AppKit                              0x00007fff81c46017 -[NSCarbonMenuImpl performActionWithHighlightingForItemAtIndex:] + 114
2016/03/08 15:02:33:435  [Error] 15  libsystem_trace.dylib               0x00007fff951c807a _os_activity_initiate + 75
2016/03/08 15:02:33:435  [Error] 16  AppKit                              0x00007fff81c44f05 -[NSMenu performKeyEquivalent:] + 357
2016/03/08 15:02:33:435  [Error] 17  AppKit                              0x00007fff81c440aa -[NSApplication _handleKeyEquivalent:] + 920
2016/03/08 15:02:33:435  [Error] 18  AppKit                              0x00007fff81b5c50f -[NSApplication sendEvent:] + 4274
2016/03/08 15:02:33:435  [Error] 19  AppKit                              0x00007fff81a8f03a -[NSApplication run] + 796
2016/03/08 15:02:33:435  [Error] 20  AppKit                              0x00007fff81a11520 NSApplicationMain + 1176
2016/03/08 15:02:33:435  [Error] 21  libdyld.dylib                       0x00007fff9490e5ad start + 1
2016/03/08 15:02:33:435  [Error] 22  ???                                 0x0000000000000001 0x0 + 1
2016/03/08 15:02:38:795  [Error] Exception reported by the runtime: -[__NSCFString replaceCharactersInRange:withString:]: nil argument
2016/03/08 15:02:38:797  [Error] 0   CoreFoundation                      0x00007fff85317ae2 __exceptionPreprocess + 178
2016/03/08 15:02:38:797  [Error] 1   libobjc.A.dylib                     0x00007fff82712f7e objc_exception_throw + 48
2016/03/08 15:02:38:797  [Error] 2   CoreFoundation                      0x00007fff8531798d +[NSException raise:format:] + 205
2016/03/08 15:02:38:797  [Error] 3   CoreFoundation                      0x00007fff852d237f mutateError + 159
2016/03/08 15:02:38:797  [Error] 4   Foundation                          0x00007fff88431002 -[NSConcreteMutableAttributedString replaceCharactersInRange:withAttributedString:] + 286
2016/03/08 15:02:38:797  [Error] 5   Pecunia                             0x0000000105fd8bf5 Pecunia + 605173
2016/03/08 15:02:38:797  [Error] 6   Pecunia                             0x0000000105fd8351 Pecunia + 602961
2016/03/08 15:02:38:797  [Error] 7   Pecunia                             0x0000000105fda0f6 Pecunia + 610550
2016/03/08 15:02:38:797  [Error] 8   Pecunia                             0x0000000105fd7936 Pecunia + 600374
2016/03/08 15:02:38:797  [Error] 9   Pecunia                             0x000000010601c142 Pecunia + 880962
2016/03/08 15:02:38:797  [Error] 10  Pecunia                             0x0000000105f4dc8c Pecunia + 35980
2016/03/08 15:02:38:797  [Error] 11  libsystem_trace.dylib               0x00007fff951c807a _os_activity_initiate + 75
2016/03/08 15:02:38:797  [Error] 12  AppKit                              0x00007fff81c4651d -[NSApplication sendAction:to:from:] + 460
2016/03/08 15:02:38:797  [Error] 13  AppKit                              0x00007fff81c462b7 -[NSMenuItem _corePerformAction] + 336
2016/03/08 15:02:38:798  [Error] 14  AppKit                              0x00007fff81c46017 -[NSCarbonMenuImpl performActionWithHighlightingForItemAtIndex:] + 114
2016/03/08 15:02:38:798  [Error] 15  libsystem_trace.dylib               0x00007fff951c807a _os_activity_initiate + 75
2016/03/08 15:02:38:798  [Error] 16  AppKit                              0x00007fff81d061f0 -[NSMenu performActionForItemAtIndex:] + 131
2016/03/08 15:02:38:798  [Error] 17  AppKit                              0x00007fff81d06163 -[NSMenu _internalPerformActionForItemAtIndex:] + 35
2016/03/08 15:02:38:798  [Error] 18  AppKit                              0x00007fff81d05fbb -[NSCarbonMenuImpl _carbonCommandProcessEvent:handlerCallRef:] + 107
2016/03/08 15:02:38:798  [Error] 19  AppKit                              0x00007fff81c2eea1 NSSLMMenuEventHandler + 708
2016/03/08 15:02:38:798  [Error] 20  HIToolbox                           0x00007fff8ab477be _ZL23DispatchEventToHandlersP14EventTargetRecP14OpaqueEventRefP14HandlerCallRec + 1231
2016/03/08 15:02:38:798  [Error] 21  HIToolbox                           0x00007fff8ab46c48 _ZL30SendEventToEventTargetInternalP14OpaqueEventRefP20OpaqueEventTargetRefP14HandlerCallRec + 404
2016/03/08 15:02:38:798  [Error] 22  HIToolbox                           0x00007fff8ab5c9e6 SendEventToEventTarget + 40
2016/03/08 15:02:38:798  [Error] 23  HIToolbox                           0x00007fff8aba699a _ZL18SendHICommandEventjPK9HICommandjjhPKvP20OpaqueEventTargetRefS5_PP14OpaqueEventRef + 411
2016/03/08 15:02:38:798  [Error] 24  HIToolbox                           0x00007fff8abd1d5b SendMenuCommandWithContextAndModifiers + 59
2016/03/08 15:02:38:798  [Error] 25  HIToolbox                           0x00007fff8abd1d0c SendMenuItemSelectedEvent + 188
2016/03/08 15:02:38:798  [Error] 26  HIToolbox                           0x00007fff8abd1be8 _ZL19FinishMenuSelectionP13SelectionDataP10MenuResultS2_ + 96
2016/03/08 15:02:38:798  [Error] 27  HIToolbox                           0x00007fff8abd2596 _ZL14MenuSelectCoreP8MenuData5PointdjPP13OpaqueMenuRefPt + 711
2016/03/08 15:02:38:798  [Error] 28  HIToolbox                           0x00007fff8abd2230 _HandleMenuSelection2 + 460
2016/03/08 15:02:38:798  [Error] 29  AppKit                              0x00007fff81b5975e _NSHandleCarbonMenuEvent + 277
2016/03/08 15:02:38:798  [Error] 30  AppKit                              0x00007fff81a99435 _DPSNextEvent + 1906
2016/03/08 15:02:38:798  [Error] 31  AppKit                              0x00007fff81e65943 -[NSApplication _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 454
2016/03/08 15:02:38:798  [Error] 32  AppKit                              0x00007fff81a8efc8 -[NSApplication run] + 682
2016/03/08 15:02:38:799  [Error] 33  AppKit                              0x00007fff81a11520 NSApplicationMain + 1176
2016/03/08 15:02:38:799  [Error] 34  libdyld.dylib                       0x00007fff9490e5ad start + 1
2016/03/08 15:02:38:799  [Error] 35  ???                                 0x0000000000000001 0x0 + 1
2016/03/08 15:02:38:799  [Error] An unhandled exception occurred: -[__NSCFString replaceCharactersInRange:withString:]: nil argument
2016/03/08 15:02:38:799  [Info] No additional information available
2016/03/08 15:02:38:799  [Error] 0   Pecunia                             0x0000000105f7d770 Pecunia + 231280
2016/03/08 15:02:38:799  [Error] 1   Pecunia                             0x0000000105f7d402 Pecunia + 230402
2016/03/08 15:02:38:799  [Error] 2   ExceptionHandling                   0x00007fff97458e73 -[NSExceptionHandler _handleException:mask:] + 171
2016/03/08 15:02:38:799  [Error] 3   ExceptionHandling                   0x00007fff97458c0f NSExceptionHandlerUncaughtExceptionHandler + 257
2016/03/08 15:02:38:799  [Error] 4   HIToolbox                           0x00007fff8ab47b0a _ZL23DispatchEventToHandlersP14EventTargetRecP14OpaqueEventRefP14HandlerCallRec + 2075
2016/03/08 15:02:38:800  [Error] 5   HIToolbox                           0x00007fff8ab46c48 _ZL30SendEventToEventTargetInternalP14OpaqueEventRefP20OpaqueEventTargetRefP14HandlerCallRec + 404
2016/03/08 15:02:38:800  [Error] 6   HIToolbox                           0x00007fff8ab5c9e6 SendEventToEventTarget + 40
2016/03/08 15:02:38:800  [Error] 7   HIToolbox                           0x00007fff8aba699a _ZL18SendHICommandEventjPK9HICommandjjhPKvP20OpaqueEventTargetRefS5_PP14OpaqueEventRef + 411
2016/03/08 15:02:38:800  [Error] 8   HIToolbox                           0x00007fff8abd1d5b SendMenuCommandWithContextAndModifiers + 59
2016/03/08 15:02:38:800  [Error] 9   HIToolbox                           0x00007fff8abd1d0c SendMenuItemSelectedEvent + 188
2016/03/08 15:02:38:800  [Error] 10  HIToolbox                           0x00007fff8abd1be8 _ZL19FinishMenuSelectionP13SelectionDataP10MenuResultS2_ + 96
2016/03/08 15:02:38:800  [Error] 11  HIToolbox                           0x00007fff8abd2596 _ZL14MenuSelectCoreP8MenuData5PointdjPP13OpaqueMenuRefPt + 711
2016/03/08 15:02:38:800  [Error] 12  HIToolbox                           0x00007fff8abd2230 _HandleMenuSelection2 + 460
2016/03/08 15:02:38:800  [Error] 13  AppKit                              0x00007fff81b5975e _NSHandleCarbonMenuEvent + 277
2016/03/08 15:02:38:800  [Error] 14  AppKit                              0x00007fff81a99435 _DPSNextEvent + 1906
2016/03/08 15:02:38:800  [Error] 15  AppKit                              0x00007fff81e65943 -[NSApplication _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 454
2016/03/08 15:02:38:800  [Error] 16  AppKit                              0x00007fff81a8efc8 -[NSApplication run] + 682
2016/03/08 15:02:38:800  [Error] 17  AppKit                              0x00007fff81a11520 NSApplicationMain + 1176
2016/03/08 15:02:38:800  [Error] 18  libdyld.dylib                       0x00007fff9490e5ad start + 1
2016/03/08 15:02:38:800  [Error] 19  ???                                 0x0000000000000001 0x0 + 1
2016/03/08 15:02:38:805  [Info] Successfully saved context.`

Viele Grüße

**Comment by mormmor** [comment]
Ich hab genau das selbe Problem: keiner Reaktion mit CMD+P und Absturz bei Aufruf übers Menü. Ich konnte einzelne Buchungen identifizieren, die nicht gedruckt werden konnten, weder einzeln noch zusammen mit anderen: beide Buchungen hatten sehr viele Zeichen im Feld "Auftraggeber", im Gegensatz zu denen die gedruckt werden konnten.

**Comment by macemmi** [comment]
fixed mit 1.2.4
