### ISSUE TITLE
CSV Export: Leere Notizen (NULL)

### ISSUE THREAD

**Issue by janstieler** [pecuniabanking/pecunia-client#457]
Hallo,
in einem CSV-Export werden leere Notizfelder als (null) ausgegeben.
Es wäre besser diese als wirklich leere Felder auszugeben.

Pecunia 1.2.3 (1.2.301)
Mac OS X 10.11.3

Viele Grüße

**Comment by macemmi** [comment]
Fixed

**Comment by janstieler** [comment]
Hi,
also in meiner aktuellen version 1.2.4 (1.2.404) bekomm ich die (null) immer noch ausgegeben.

**Comment by macemmi** [comment]
bitte mal die 1.3.0 probieren, die steht jetzt auf unserer Homepage zum Download bereit.

Mit freundlichen Grüßen
Frank Emminghaus

Pecunia Development & Support
http://www.pecuniabanking.de

**Comment by janstieler** [comment]
Hallo Frank,

vielen Dank, version 1.3.0 funktioniert ohne Ausgabe von NULL.

Viele Grüße
