### ISSUE TITLE
CSV-Export: Kategorien exportieren Tags nicht die Kategorien

### ISSUE THREAD

**Issue by janstieler** [pecuniabanking/pecunia-client#458]
Hallo,

das CSV Feld Kategorien exportiert die Tags (Schlagwörter) und nicht die zugewiesenen Kategorien welche man im linken Hauptfenster sieht.
Es wäre ganz gut wenn man beide Informationen mit ausgeben könnte.

Viele Grüße

**Comment by macemmi** [comment]
Nee, es werden die Kategorien exportiert. Die Tags können gar nicht exportiert werden, das ist nicht unterstützt.
