### ISSUE TITLE
Girokonten-Einstellung bei zwei Giros verwendet den gleichen Link `#bug`

### ISSUE THREAD

**Issue by johamac** [pecuniabanking/pecunia-client#459]
#kein unterschied in der darstellung der girokonten auf der startseite, der rest funktioniert einwandfrei. die beiden links der unterschiedlichen girokonten für immer auf das gleiche konto.   macbook pro mid 2010, mac os 10.11.4

bild 1 link auf das gleiche girokonto, sollten müssten aber unterschiedlich sein
bild 2 alles ok, kein giro verwendet
![bildschirmfoto 2016-04-09 um 13 41 19](https://cloud.githubusercontent.com/assets/18364294/14403503/f91d28c8-fe58-11e5-924e-2c89890530df.png)
![bildschirmfoto 2016-04-09 um 13 41 47](https://cloud.githubusercontent.com/assets/18364294/14403504/ffaada00-fe58-11e5-9314-f35ef5cfc1c1.png)

wäre nett, wenn mir jemand verrät, wie ich das label BUG vergeben kann, danke

**Comment by mike-lischke** [comment]
IIRC die Auswahl erfolgt auf Basis des Namens. Der erste gefundene gewinnt. Also am besten verschieden Kontennamen verwenden.

**Comment by johamac** [comment]
funktioniert. danke für die Hilfe! :-)))
