### ISSUE TITLE
Viele Errors im Logfile dokumentiert

### ISSUE THREAD

**Issue by terraner** [pecuniabanking/pecunia-client#476]
2016/10/02 10:06:58:684  [Error] Caught signal 4
2016/10/02 10:06:58:688  [Error] 0   Pecunia                             0x000000010b873026 Pecunia + 237606
2016/10/02 10:06:58:688  [Error] 1   Pecunia                             0x000000010b853285 Pecunia + 107141
2016/10/02 10:06:58:689  [Error] 2   libsystem_platform.dylib            0x00007fffa1664bba _sigtramp + 26
2016/10/02 10:06:58:689  [Error] 3   ???                                 0x00007fff543c3058 0x0 + 140734606618712
2016/10/02 10:06:58:689  [Error] 4   Pecunia                             0x000000010ba01019 Pecunia + 1867801
2016/10/02 10:06:58:689  [Error] 5   Pecunia                             0x000000010b85054d Pecunia + 95565
2016/10/02 10:06:58:689  [Error] 6   Foundation                          0x00007fff8ddc3dbd NSKeyValueNotifyObserver + 350
2016/10/02 10:06:58:689  [Error] 7   Foundation                          0x00007fff8ddc3654 NSKeyValueDidChange + 486
2016/10/02 10:06:58:689  [Error] 8   Foundation                          0x00007fff8df022d7 -[NSObject(NSKeyValueObservingPrivate) _changeValueForKeys:count:maybeOldValuesDict:usingBlock:] + 944
2016/10/02 10:06:58:689  [Error] 9   Foundation                          0x00007fff8df01c2a -[NSObject(NSKeyValueObservingPrivate) _notifyObserversOfChangeFromValuesForKeys:toValuesForKeys:] + 807
2016/10/02 10:06:58:689  [Error] 10  CoreFoundation                      0x00007fff8c46672a forEachObserver + 298
2016/10/02 10:06:58:689  [Error] 11  CoreFoundation                      0x00007fff8c466948 -[CFPrefsSource _notifyObserversOfChangeFromValuesForKeys:toValuesForKeys:] + 72
2016/10/02 10:06:58:689  [Error] 12  CoreFoundation                      0x00007fff8c4b4e22 __84-[CFPrefsSearchListSource asynchronouslyNotifyOfChangesFromDictionary:toDictionary:]_block_invoke_2 + 34
2016/10/02 10:06:58:690  [Error] 13  CoreFoundation                      0x00007fff8c3a63cc __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ + 12
2016/10/02 10:06:58:690  [Error] 14  CoreFoundation                      0x00007fff8c3876f4 __CFRunLoopDoBlocks + 356
2016/10/02 10:06:58:690  [Error] 15  CoreFoundation                      0x00007fff8c386e65 __CFRunLoopRun + 917
2016/10/02 10:06:58:690  [Error] 16  CoreFoundation                      0x00007fff8c386874 CFRunLoopRunSpecific + 420
2016/10/02 10:06:58:690  [Error] 17  HIToolbox                           0x00007fff8b926f6c RunCurrentEventLoopInMode + 240
2016/10/02 10:06:58:690  [Error] 18  HIToolbox                           0x00007fff8b926ca9 ReceiveNextEventCommon + 184
2016/10/02 10:06:58:690  [Error] 19  HIToolbox                           0x00007fff8b926bd6 _BlockUntilNextEventMatchingListInModeWithFilter + 71
2016/10/02 10:06:58:690  [Error] 20  AppKit                              0x00007fff8a01d5f5 _DPSNextEvent + 1093
2016/10/02 10:06:58:690  [Error] 21  AppKit                              0x00007fff8a72d8eb -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1637
2016/10/02 10:06:58:690  [Error] 22  AppKit                              0x00007fff8a2737b0 -[NSApplication _doModalLoop:peek:] + 497
2016/10/02 10:06:58:691  [Error] 23  AppKit                              0x00007fff8a445c36 __35-[NSApplication runModalForWindow:]_block_invoke + 64
2016/10/02 10:06:58:691  [Error] 24  AppKit                              0x00007fff8a271316 -[NSApplication runModalForWindow:] + 137
2016/10/02 10:06:58:691  [Error] 25  Pecunia                             0x000000010b87c722 Pecunia + 276258
2016/10/02 10:06:58:691  [Error] 26  Pecunia                             0x000000010b84d798 Pecunia + 83864
2016/10/02 10:06:58:691  [Error] 27  CoreFoundation                      0x00007fff8c39c6ac __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 12
2016/10/02 10:06:58:691  [Error] 28  CoreFoundation                      0x00007fff8c39c5ab _CFXRegistrationPost + 427
2016/10/02 10:06:58:691  [Error] 29  CoreFoundation                      0x00007fff8c39c312 ___CFXNotificationPost_block_invoke + 50
2016/10/02 10:06:58:691  [Error] 30  CoreFoundation                      0x00007fff8c35aa32 -[_CFXNotificationRegistrar find:object:observer:enumerator:] + 2018
2016/10/02 10:06:58:691  [Error] 31  CoreFoundation                      0x00007fff8c359a1b _CFXNotificationPost + 667
2016/10/02 10:06:58:691  [Error] 32  Foundation                          0x00007fff8dd870e3 -[NSNotificationCenter postNotificationName:object:userInfo:] + 66
2016/10/02 10:06:58:691  [Error] 33  AppKit                              0x00007fff8a15e7e5 -[NSApplication _postDidFinishNotification] + 297
2016/10/02 10:06:58:691  [Error] 34  AppKit                              0x00007fff8a15e54a -[NSApplication _sendFinishLaunchingNotification] + 208
2016/10/02 10:06:58:691  [Error] 35  AppKit                              0x00007fff8a0224e3 -[NSApplication(NSAppleEventHandling) _handleAEOpenEvent:] + 552
2016/10/02 10:06:58:692  [Error] 36  AppKit                              0x00007fff8a022138 -[NSApplication(NSAppleEventHandling) _handleCoreEvent:withReplyEvent:] + 661
2016/10/02 10:06:58:692  [Error] 37  Foundation                          0x00007fff8ddd255d -[NSAppleEventManager dispatchRawAppleEvent:withRawReply:handlerRefCon:] + 290
2016/10/02 10:06:58:692  [Error] 38  Foundation                          0x00007fff8ddd23d7 _NSAppleEventManagerGenericHandler + 102
2016/10/02 10:06:58:692  [Error] 39  AE                                  0x00007fff8d1da46a _Z20aeDispatchAppleEventPK6AEDescPS_jPh + 544
2016/10/02 10:06:58:692  [Error] 40  AE                                  0x00007fff8d1da1e1 _ZL25dispatchEventAndSendReplyPK6AEDescPS_ + 39
2016/10/02 10:06:58:692  [Error] 41  AE                                  0x00007fff8d1da0ed aeProcessAppleEvent + 312
2016/10/02 10:06:58:692  [Error] 42  HIToolbox                           0x00007fff8b93769f AEProcessAppleEvent + 55
2016/10/02 10:06:58:692  [Error] 43  AppKit                              0x00007fff8a01d8c3 _DPSNextEvent + 1811
2016/10/02 10:06:58:692  [Error] 44  AppKit                              0x00007fff8a72d8eb -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1637
2016/10/02 10:06:58:692  [Error] 45  AppKit                              0x00007fff8a011fbd -[NSApplication run] + 926
2016/10/02 10:06:58:692  [Error] 46  AppKit                              0x00007fff89fdca8a NSApplicationMain + 1237
2016/10/02 10:06:58:692  [Error] 47  libdyld.dylib                       0x00007fffa1458255 start + 1
2016/10/02 10:06:58:692  [Error] Failed to save context. Reason: (null)

**Comment by mike-lischke** [comment]
Das sind nicht viele Fehler, sondern nur einer, dargestellt durch einen stack trace. Allerdings ohne genauere Beschreibung, was genau getan wurde und was geschah kann niemand damit etwas anfangen. Besser ist es also den Fehler im Detail zu beschreiben. Öffne den Bug report einfach wieder, wenn du so eine Beschreibung liefern kannst.

**Comment by terraner** [comment]
Der Fehler tritt bei jedem Start der Applikation auf. Auch ohne eine Aktion in Pecunia zu starten

**Comment by mike-lischke** [comment]
Duplikat von #469.
