### ISSUE TITLE
SEPA-Umbuchung lässt sich nicht bearbeiten

### ISSUE THREAD

**Issue by Bombe** [pecuniabanking/pecunia-client#478]
Pecunia 1.2.4 (1.2.400), OS X 10.9.5.

Ich versuche, für mein Konto bei der Deutschen Bank eine Umbuchung auszuführen. Ich ziehe also unter dem Punkt „Überweisungen“ das entsprechende Formular in den Zielbereich, kann es dort aber nicht bearbeiten: Keine der Eingabekomponenten ist fokussierbar, die beiden Buttons unten drunter sind disabled. Ich kann das Formular aber wieder dort weg ziehen, z.B. in den Papierkorb.

Das Formular für normale SEPA-Überweisungen funktioniert einwandfrei.

**Comment by mike-lischke** [comment]
Die Kontoauswahl führt nur Konten für die eine Umbuchung möglich ist. Das legt das Kreditinstitut fest. Immer wieder hören wir auch von Banken, die eine Umbuchung per Web erlauben, aber nicht via HBCI. In solchen Fällen sind Banking Apps machtlos. Allerdings kann man auch noch versuchen die BPD zu aktualisieren (siehe Bankkennungen) über die die Bank unterstützte Geschäftsvorfälle annonciert. Vielleicht fehlte ja bisher nur der Umbuchungs GV.

**Comment by Bombe** [comment]
Synchronisieren des Account in den Bankkennungen hat leider nichts geändert. Schade!
