### ISSUE TITLE
Keine Umsatzabfrage DKB-Bank

### ISSUE THREAD

**Issue by Schnappa** [pecuniabanking/pecunia-client#487]
Mit der neuen Version 1.3.1 ist es immer noch nicht möglich, Umsätze von der DKB-Bank abzurufen. Fehlerbericht habe ich gesendet.

**Comment by osopolar** [comment]
Ich habe Version 1.3.1 (1.3.101) und da funktioniert die Abfrage des DKB-Kontos.

@Schnappa Welche HBCI Version ist denn bei Dir eingestellt? Ich erinnere mich, dass es hier bei der DKB eine Umstellung gab.

Ich verwende in den Bankkennungen folgende Einstellungen:

Bank URL: https://banking-dkb.s-fints-pt-dkb.de/fints30
HBCI Version: 300
☑ Base64 Kodierung
☑ Zertifikat prüfen

**Comment by Schnappa** [comment]
Ich hatte den Entwickler angeschrieben, der mir empfohlen hat, das Programm zu wechseln, da er bei den ständigen Änderungen der DKB nicht mehr hinterherkommt. Das habe ich getan.

Ich habe aber die selbe Programmversion und dort die selben Einstellungen eingetragen, wie Du. Die Umsätze werden trotzdem nicht abgerufen.

**Comment by PaulStu** [comment]
Geht es um das DKB-Girokonto oder um das Kreditkartenkonto? Das Kreditkartenkonto wird nämlich nicht der HBCI abgerufen. Beides funktioniert bei mir mit der aktuellen Version allerdings ohne Probleme. Ist beim Kreditkartenkonto als Kontotyp "DKB Kreditkartenkonto" oder "Standardkonto" eingestellt?

**Comment by Schnappa** [comment]
Es geht um das Girokonto.

**Comment by derkostka** [comment]
Ich bin noch auf Version 1.3.100.
Die Einstellungen der DKB sind bei mir noch auf:
HBCI: 220
URL: https://hbci-pintan-by.s-hbci.de/PinTanServlet

-> Die VISA Abfrage klappt, aber die Giroumsätze nicht. 

Wie kann ich denn die Einstellungen der Bankkennung ändern ? Woher bekomme ich die 1.3.101 ?

**Comment by kl-git** [comment]
Hallo zusammen,

gleiches Problem hier:
`2017/04/01 19:32:46:796  [Verbose] Parsed message result:`
`2017/04/01 19:33:05:646  [Info] Login process triggered`
`2017/04/01 19:33:08:715  [Error] Unknown URL, couldn't get credit card overview`

bzw.: 
`2017/04/03 11:44:41:327  [Info] Pecunia version: 1.3.1`
`2017/04/03 11:44:41:327  [Info] Pecunia build version: 1.3.100`
[...]
`2017/04/03 11:45:02:768  [Info] Login process triggered`
`2017/04/03 11:47:25:386  [Error] TypeError: undefined is not an object (evaluating 'list.length')`

Bankenkennung syncronisiert - HBCI 300
<img width="431" alt="pecunia dkb visa error" src="https://cloud.githubusercontent.com/assets/10635751/24604430/f50b7042-1864-11e7-8be9-ddb2ae70d6b6.png">

Jeder Hinweis wie man das fixen kann ist hoch willkommen.

Viele Grüße,

Klaus

**Comment by PaulStu** [comment]
@kl-git Der Fehler, den du beschreibst, ist ein anderer, das Kreditkartenkonto wird nicht per HBCI abgerufen. Die DKB hat aktuell Probleme mit dem Login fürs Onlinebanking, versuch es am besten nochmal, wenn das wieder funktioniert:
[https://www.dkb.de/banking](url)

**Comment by kl-git** [comment]
@PaulStu - Danke für den Hinweis. Läuft wieder. Viele Grüße

**Comment by foss-** [comment]
DKB funktioniert hier korrekt. Besteht das ursprüngliche Problem mit Pecunia 1.3.2 noch fort oder kann der Issue geschlossen werden?

**Comment by Schnappa** [comment]
Da ich Pecunia nicht mehr einsetze, weiß ich nicht, ob das Problem mittlerweile behoben wurde. Falls dem so ist, kann das Ticket geschlossen werden.

Steffen

**Comment by kl-git** [comment]
1.3.210 gerade getestet --> funktioniert

**Comment by foss-** [comment]
brauchen wir nur noch jemanden mit rechten den issue zu schließen...
