### ISSUE TITLE
Programm darf nicht drucken

### ISSUE THREAD

**Issue by fuchsws** [pecuniabanking/pecunia-client#496]
Beim Versuch zu drucken (egal was) erscheint die Meldung:

"Diese Programm darf nicht drucken.
Wenden Sie sich an den Softwarehändler und fragen Sie nach einem Update"

Pecunia 1.3.1 aus dem AppStore

![bildschirmfoto 2017-03-29 um 14 38 12](https://cloud.githubusercontent.com/assets/2485956/24454780/6ee4a0fe-148d-11e7-8610-3d171f00d171.jpg)

**Comment by nachtgold** [comment]
Ich habe eben auf Version 1.3.3 aktualisiert, die man auf deren Webseite bekommt. Ich kann nun wieder drucken, versuch das mal.

**Comment by fuchsws** [comment]
Geht inzwischen wieder
