### ISSUE TITLE
Pecunia 1.3.3 csv-Dateien nach Update leer

### ISSUE THREAD

**Issue by carsten-wenderdel** [pecuniabanking/pecunia-client#504]
Umgebung: macOS Sierra, Pecunia 1.3.3

Wenn ich versuche ein Konto zu exportieren, dann wird eine fast leere csv-Datei erstellt. Inhalt sind nur Zeilenumbrüche, deren Anzahl scheint der Anzahl der Transaktionen zu entsprechen.

Wenn ich in Einstellungen auf `Export` gehe, dann kann ich bei `Exportierte Felder` nichts hinzufügen, alles erscheint leer. Ist das normal?

Ich würde mir gerne das mit dem Debugger anschauen (ich arbeite als iOS-Entwickler). Leider baut das Projekt nicht bei mir (Siehe #503)

**Comment by hwde** [comment]
Hallo Carsten,

ich hatte das Problem auch, irgendwo (per Google gefunden) war ein Post von Mike oder Frank das es an einem der Export-Felder liegt die das Problem verursachen. Sobald man dieses Feld nicht mehr exportiert, klappt es. Hier die Liste der Felder aus meinen Einstellungen die problemlos exportiert werden konnten:

Valutadatum
Buchungsdatum
Wert
Saldo
Währung
Konto
Bankleitzahl
Kontoname
Land
Suffix
Empfänger
Verwendungszweck
Notiz
Empfängerkonto
Bankleitzahl Empfängerbank
Name Empfängerbank
IBAN Empfänger
BIC Empfänger
Suffix Empfänger
Kundenreferernz
Bankreferenz

Welches der nicht verwendeten das Problem verursacht hat habe ich dann nicht mehr untersucht, mir reichte der Export.

**Comment by carsten-wenderdel** [comment]
Das Problem hat sich erledigt, ich hatte in der UI nicht die Möglichkeit gefunden, Felder hinzuzufügen. Wenn man unter Einstellungen auf `+` klickt, kommt ein leeres Feld. Das kann man aber noch selektieren und dort das entsprechende Feld wählen.
