### ISSUE TITLE
DKB Umsatzabfrage mit Debit VISA

### ISSUE THREAD

**Issue by Indiana8000** [pecuniabanking/pecunia-client#531]
Hi,

Seit neustem wird mir bei VISA Buchungen nicht mehr der Abweichende Auftraggeber angezeigt/geladen.
Mit der alten Version 2.0.x hat das noch funktioniert.

Hier die Diskusion im Homebanking Forum:
https://homebanking-hilfe.de/forum/topic.php?t=25599

Grüße
![DKB_HBCI_OK](https://user-images.githubusercontent.com/649041/222171030-80e3c8e4-8c0b-4112-8e45-a68c380f15bb.png)
![DKB_HBCI_Problem](https://user-images.githubusercontent.com/649041/222171038-49ab229b-e3d7-447a-b0c1-6cbed515486d.png)

**Comment by Indiana8000** [comment]
Antwort von DKB zu dem Problem lautet:
Bitte deaktivieren Sie den Abruf der Umsätze über das MT940 Protokoll.

**Comment by foss-** [comment]
Laut Forenkommentar vom 05.05.2023 wurde das Problem gelöst. Kannst du das bestätigen und kann damit der Issue hier geschlossen werden @Indiana8000 ?

**Comment by Indiana8000** [comment]
Sorry deine Nachricht erst jetzt gesehen. Hab aktuell leider keine Mac-Entwicklungsumgebung mehr. Wenn 34.02 zum Download verfügbar ist kann ich das aber gerne Testen.

**Comment by foss-** [comment]
Pecunia 2.1.6 (Build 35.03) wurde veröffentlicht:
https://pecuniabanking.de/index.php/downloads
Könntest du diese Version testen?

**Comment by Indiana8000** [comment]
Funktioniert wieder. Das Feld "Abwechender Empfänger" ist wieder gefüllt.

Sorry für die späte Antwort.

**Comment by foss-** [comment]
Super, dann kannst du den Issue hier schließen.
